package com.spring.mpvue.springbootmpvue.sqlserver.mapper;

import com.spring.mpvue.springbootmpvue.sqlserver.po.UdsHourse;
import com.spring.mpvue.springbootmpvue.sqlserver.po.UdsHourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UdsHourseMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int countByExample(UdsHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int deleteByExample(UdsHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int insert(UdsHourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int insertSelective(UdsHourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    List<UdsHourse> selectByExample(UdsHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    UdsHourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") UdsHourse record, @Param("example") UdsHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int updateByExample(@Param("record") UdsHourse record, @Param("example") UdsHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int updateByPrimaryKeySelective(UdsHourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int updateByPrimaryKey(UdsHourse record);
}