package com.spring.mpvue.springbootmpvue.sqlserver.mapper;

import com.spring.mpvue.springbootmpvue.sqlserver.po.UdsTaskGjd;
import com.spring.mpvue.springbootmpvue.sqlserver.po.UdsTaskGjdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UdsTaskGjdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int countByExample(UdsTaskGjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int deleteByExample(UdsTaskGjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int deleteByPrimaryKey(Integer gjdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int insert(UdsTaskGjd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int insertSelective(UdsTaskGjd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    List<UdsTaskGjd> selectByExample(UdsTaskGjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    UdsTaskGjd selectByPrimaryKey(Integer gjdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") UdsTaskGjd record, @Param("example") UdsTaskGjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int updateByExample(@Param("record") UdsTaskGjd record, @Param("example") UdsTaskGjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int updateByPrimaryKeySelective(UdsTaskGjd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uds_task_gjd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    int updateByPrimaryKey(UdsTaskGjd record);
}