server:
  port: 18080

spring:
    datasource:
        url: jdbc:mysql://120.77.174.180:3306/dbspringboot?characterEncoding=utf-8
        username: root
        password: 12345a

#自定义配置
resources:
    logdir: logs/
    midpHost: 1.1.1.1
