spring:
 datasource:
 # 连接数据库的url
    url: jdbc:mysql://localhost:3306/dbspringboot?characterEncoding=utf-8
    # 连接数据库的用户名
    username: root
    # 连接数据库的密码
    password: 12345a
# 服务器端口号
server:
    port: 8081
