package com.spring.mpvue.springbootmpvue.sqlserver.po;

import java.util.ArrayList;
import java.util.List;

public class UdsHourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public UdsHourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRealestateidIsNull() {
            addCriterion("REALESTATEID is null");
            return (Criteria) this;
        }

        public Criteria andRealestateidIsNotNull() {
            addCriterion("REALESTATEID is not null");
            return (Criteria) this;
        }

        public Criteria andRealestateidEqualTo(Integer value) {
            addCriterion("REALESTATEID =", value, "realestateid");
            return (Criteria) this;
        }

        public Criteria andRealestateidNotEqualTo(Integer value) {
            addCriterion("REALESTATEID <>", value, "realestateid");
            return (Criteria) this;
        }

        public Criteria andRealestateidGreaterThan(Integer value) {
            addCriterion("REALESTATEID >", value, "realestateid");
            return (Criteria) this;
        }

        public Criteria andRealestateidGreaterThanOrEqualTo(Integer value) {
            addCriterion("REALESTATEID >=", value, "realestateid");
            return (Criteria) this;
        }

        public Criteria andRealestateidLessThan(Integer value) {
            addCriterion("REALESTATEID <", value, "realestateid");
            return (Criteria) this;
        }

        public Criteria andRealestateidLessThanOrEqualTo(Integer value) {
            addCriterion("REALESTATEID <=", value, "realestateid");
            return (Criteria) this;
        }

        public Criteria andRealestateidIn(List<Integer> values) {
            addCriterion("REALESTATEID in", values, "realestateid");
            return (Criteria) this;
        }

        public Criteria andRealestateidNotIn(List<Integer> values) {
            addCriterion("REALESTATEID not in", values, "realestateid");
            return (Criteria) this;
        }

        public Criteria andRealestateidBetween(Integer value1, Integer value2) {
            addCriterion("REALESTATEID between", value1, value2, "realestateid");
            return (Criteria) this;
        }

        public Criteria andRealestateidNotBetween(Integer value1, Integer value2) {
            addCriterion("REALESTATEID not between", value1, value2, "realestateid");
            return (Criteria) this;
        }

        public Criteria andBuildIsNull() {
            addCriterion("build is null");
            return (Criteria) this;
        }

        public Criteria andBuildIsNotNull() {
            addCriterion("build is not null");
            return (Criteria) this;
        }

        public Criteria andBuildEqualTo(String value) {
            addCriterion("build =", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildNotEqualTo(String value) {
            addCriterion("build <>", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildGreaterThan(String value) {
            addCriterion("build >", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildGreaterThanOrEqualTo(String value) {
            addCriterion("build >=", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildLessThan(String value) {
            addCriterion("build <", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildLessThanOrEqualTo(String value) {
            addCriterion("build <=", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildLike(String value) {
            addCriterion("build like", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildNotLike(String value) {
            addCriterion("build not like", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildIn(List<String> values) {
            addCriterion("build in", values, "build");
            return (Criteria) this;
        }

        public Criteria andBuildNotIn(List<String> values) {
            addCriterion("build not in", values, "build");
            return (Criteria) this;
        }

        public Criteria andBuildBetween(String value1, String value2) {
            addCriterion("build between", value1, value2, "build");
            return (Criteria) this;
        }

        public Criteria andBuildNotBetween(String value1, String value2) {
            addCriterion("build not between", value1, value2, "build");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTdsyIsNull() {
            addCriterion("tdsy is null");
            return (Criteria) this;
        }

        public Criteria andTdsyIsNotNull() {
            addCriterion("tdsy is not null");
            return (Criteria) this;
        }

        public Criteria andTdsyEqualTo(String value) {
            addCriterion("tdsy =", value, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyNotEqualTo(String value) {
            addCriterion("tdsy <>", value, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyGreaterThan(String value) {
            addCriterion("tdsy >", value, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyGreaterThanOrEqualTo(String value) {
            addCriterion("tdsy >=", value, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyLessThan(String value) {
            addCriterion("tdsy <", value, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyLessThanOrEqualTo(String value) {
            addCriterion("tdsy <=", value, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyLike(String value) {
            addCriterion("tdsy like", value, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyNotLike(String value) {
            addCriterion("tdsy not like", value, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyIn(List<String> values) {
            addCriterion("tdsy in", values, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyNotIn(List<String> values) {
            addCriterion("tdsy not in", values, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyBetween(String value1, String value2) {
            addCriterion("tdsy between", value1, value2, "tdsy");
            return (Criteria) this;
        }

        public Criteria andTdsyNotBetween(String value1, String value2) {
            addCriterion("tdsy not between", value1, value2, "tdsy");
            return (Criteria) this;
        }

        public Criteria andCbIsNull() {
            addCriterion("cb is null");
            return (Criteria) this;
        }

        public Criteria andCbIsNotNull() {
            addCriterion("cb is not null");
            return (Criteria) this;
        }

        public Criteria andCbEqualTo(String value) {
            addCriterion("cb =", value, "cb");
            return (Criteria) this;
        }

        public Criteria andCbNotEqualTo(String value) {
            addCriterion("cb <>", value, "cb");
            return (Criteria) this;
        }

        public Criteria andCbGreaterThan(String value) {
            addCriterion("cb >", value, "cb");
            return (Criteria) this;
        }

        public Criteria andCbGreaterThanOrEqualTo(String value) {
            addCriterion("cb >=", value, "cb");
            return (Criteria) this;
        }

        public Criteria andCbLessThan(String value) {
            addCriterion("cb <", value, "cb");
            return (Criteria) this;
        }

        public Criteria andCbLessThanOrEqualTo(String value) {
            addCriterion("cb <=", value, "cb");
            return (Criteria) this;
        }

        public Criteria andCbLike(String value) {
            addCriterion("cb like", value, "cb");
            return (Criteria) this;
        }

        public Criteria andCbNotLike(String value) {
            addCriterion("cb not like", value, "cb");
            return (Criteria) this;
        }

        public Criteria andCbIn(List<String> values) {
            addCriterion("cb in", values, "cb");
            return (Criteria) this;
        }

        public Criteria andCbNotIn(List<String> values) {
            addCriterion("cb not in", values, "cb");
            return (Criteria) this;
        }

        public Criteria andCbBetween(String value1, String value2) {
            addCriterion("cb between", value1, value2, "cb");
            return (Criteria) this;
        }

        public Criteria andCbNotBetween(String value1, String value2) {
            addCriterion("cb not between", value1, value2, "cb");
            return (Criteria) this;
        }

        public Criteria andJgIsNull() {
            addCriterion("jg is null");
            return (Criteria) this;
        }

        public Criteria andJgIsNotNull() {
            addCriterion("jg is not null");
            return (Criteria) this;
        }

        public Criteria andJgEqualTo(String value) {
            addCriterion("jg =", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgNotEqualTo(String value) {
            addCriterion("jg <>", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgGreaterThan(String value) {
            addCriterion("jg >", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgGreaterThanOrEqualTo(String value) {
            addCriterion("jg >=", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgLessThan(String value) {
            addCriterion("jg <", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgLessThanOrEqualTo(String value) {
            addCriterion("jg <=", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgLike(String value) {
            addCriterion("jg like", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgNotLike(String value) {
            addCriterion("jg not like", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgIn(List<String> values) {
            addCriterion("jg in", values, "jg");
            return (Criteria) this;
        }

        public Criteria andJgNotIn(List<String> values) {
            addCriterion("jg not in", values, "jg");
            return (Criteria) this;
        }

        public Criteria andJgBetween(String value1, String value2) {
            addCriterion("jg between", value1, value2, "jg");
            return (Criteria) this;
        }

        public Criteria andJgNotBetween(String value1, String value2) {
            addCriterion("jg not between", value1, value2, "jg");
            return (Criteria) this;
        }

        public Criteria andZcsIsNull() {
            addCriterion("zcs is null");
            return (Criteria) this;
        }

        public Criteria andZcsIsNotNull() {
            addCriterion("zcs is not null");
            return (Criteria) this;
        }

        public Criteria andZcsEqualTo(String value) {
            addCriterion("zcs =", value, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsNotEqualTo(String value) {
            addCriterion("zcs <>", value, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsGreaterThan(String value) {
            addCriterion("zcs >", value, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsGreaterThanOrEqualTo(String value) {
            addCriterion("zcs >=", value, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsLessThan(String value) {
            addCriterion("zcs <", value, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsLessThanOrEqualTo(String value) {
            addCriterion("zcs <=", value, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsLike(String value) {
            addCriterion("zcs like", value, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsNotLike(String value) {
            addCriterion("zcs not like", value, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsIn(List<String> values) {
            addCriterion("zcs in", values, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsNotIn(List<String> values) {
            addCriterion("zcs not in", values, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsBetween(String value1, String value2) {
            addCriterion("zcs between", value1, value2, "zcs");
            return (Criteria) this;
        }

        public Criteria andZcsNotBetween(String value1, String value2) {
            addCriterion("zcs not between", value1, value2, "zcs");
            return (Criteria) this;
        }

        public Criteria andPgcIsNull() {
            addCriterion("pgc is null");
            return (Criteria) this;
        }

        public Criteria andPgcIsNotNull() {
            addCriterion("pgc is not null");
            return (Criteria) this;
        }

        public Criteria andPgcEqualTo(String value) {
            addCriterion("pgc =", value, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcNotEqualTo(String value) {
            addCriterion("pgc <>", value, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcGreaterThan(String value) {
            addCriterion("pgc >", value, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcGreaterThanOrEqualTo(String value) {
            addCriterion("pgc >=", value, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcLessThan(String value) {
            addCriterion("pgc <", value, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcLessThanOrEqualTo(String value) {
            addCriterion("pgc <=", value, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcLike(String value) {
            addCriterion("pgc like", value, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcNotLike(String value) {
            addCriterion("pgc not like", value, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcIn(List<String> values) {
            addCriterion("pgc in", values, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcNotIn(List<String> values) {
            addCriterion("pgc not in", values, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcBetween(String value1, String value2) {
            addCriterion("pgc between", value1, value2, "pgc");
            return (Criteria) this;
        }

        public Criteria andPgcNotBetween(String value1, String value2) {
            addCriterion("pgc not between", value1, value2, "pgc");
            return (Criteria) this;
        }

        public Criteria andDhIsNull() {
            addCriterion("dh is null");
            return (Criteria) this;
        }

        public Criteria andDhIsNotNull() {
            addCriterion("dh is not null");
            return (Criteria) this;
        }

        public Criteria andDhEqualTo(String value) {
            addCriterion("dh =", value, "dh");
            return (Criteria) this;
        }

        public Criteria andDhNotEqualTo(String value) {
            addCriterion("dh <>", value, "dh");
            return (Criteria) this;
        }

        public Criteria andDhGreaterThan(String value) {
            addCriterion("dh >", value, "dh");
            return (Criteria) this;
        }

        public Criteria andDhGreaterThanOrEqualTo(String value) {
            addCriterion("dh >=", value, "dh");
            return (Criteria) this;
        }

        public Criteria andDhLessThan(String value) {
            addCriterion("dh <", value, "dh");
            return (Criteria) this;
        }

        public Criteria andDhLessThanOrEqualTo(String value) {
            addCriterion("dh <=", value, "dh");
            return (Criteria) this;
        }

        public Criteria andDhLike(String value) {
            addCriterion("dh like", value, "dh");
            return (Criteria) this;
        }

        public Criteria andDhNotLike(String value) {
            addCriterion("dh not like", value, "dh");
            return (Criteria) this;
        }

        public Criteria andDhIn(List<String> values) {
            addCriterion("dh in", values, "dh");
            return (Criteria) this;
        }

        public Criteria andDhNotIn(List<String> values) {
            addCriterion("dh not in", values, "dh");
            return (Criteria) this;
        }

        public Criteria andDhBetween(String value1, String value2) {
            addCriterion("dh between", value1, value2, "dh");
            return (Criteria) this;
        }

        public Criteria andDhNotBetween(String value1, String value2) {
            addCriterion("dh not between", value1, value2, "dh");
            return (Criteria) this;
        }

        public Criteria andTnIsNull() {
            addCriterion("tn is null");
            return (Criteria) this;
        }

        public Criteria andTnIsNotNull() {
            addCriterion("tn is not null");
            return (Criteria) this;
        }

        public Criteria andTnEqualTo(String value) {
            addCriterion("tn =", value, "tn");
            return (Criteria) this;
        }

        public Criteria andTnNotEqualTo(String value) {
            addCriterion("tn <>", value, "tn");
            return (Criteria) this;
        }

        public Criteria andTnGreaterThan(String value) {
            addCriterion("tn >", value, "tn");
            return (Criteria) this;
        }

        public Criteria andTnGreaterThanOrEqualTo(String value) {
            addCriterion("tn >=", value, "tn");
            return (Criteria) this;
        }

        public Criteria andTnLessThan(String value) {
            addCriterion("tn <", value, "tn");
            return (Criteria) this;
        }

        public Criteria andTnLessThanOrEqualTo(String value) {
            addCriterion("tn <=", value, "tn");
            return (Criteria) this;
        }

        public Criteria andTnLike(String value) {
            addCriterion("tn like", value, "tn");
            return (Criteria) this;
        }

        public Criteria andTnNotLike(String value) {
            addCriterion("tn not like", value, "tn");
            return (Criteria) this;
        }

        public Criteria andTnIn(List<String> values) {
            addCriterion("tn in", values, "tn");
            return (Criteria) this;
        }

        public Criteria andTnNotIn(List<String> values) {
            addCriterion("tn not in", values, "tn");
            return (Criteria) this;
        }

        public Criteria andTnBetween(String value1, String value2) {
            addCriterion("tn between", value1, value2, "tn");
            return (Criteria) this;
        }

        public Criteria andTnNotBetween(String value1, String value2) {
            addCriterion("tn not between", value1, value2, "tn");
            return (Criteria) this;
        }

        public Criteria andFtIsNull() {
            addCriterion("ft is null");
            return (Criteria) this;
        }

        public Criteria andFtIsNotNull() {
            addCriterion("ft is not null");
            return (Criteria) this;
        }

        public Criteria andFtEqualTo(String value) {
            addCriterion("ft =", value, "ft");
            return (Criteria) this;
        }

        public Criteria andFtNotEqualTo(String value) {
            addCriterion("ft <>", value, "ft");
            return (Criteria) this;
        }

        public Criteria andFtGreaterThan(String value) {
            addCriterion("ft >", value, "ft");
            return (Criteria) this;
        }

        public Criteria andFtGreaterThanOrEqualTo(String value) {
            addCriterion("ft >=", value, "ft");
            return (Criteria) this;
        }

        public Criteria andFtLessThan(String value) {
            addCriterion("ft <", value, "ft");
            return (Criteria) this;
        }

        public Criteria andFtLessThanOrEqualTo(String value) {
            addCriterion("ft <=", value, "ft");
            return (Criteria) this;
        }

        public Criteria andFtLike(String value) {
            addCriterion("ft like", value, "ft");
            return (Criteria) this;
        }

        public Criteria andFtNotLike(String value) {
            addCriterion("ft not like", value, "ft");
            return (Criteria) this;
        }

        public Criteria andFtIn(List<String> values) {
            addCriterion("ft in", values, "ft");
            return (Criteria) this;
        }

        public Criteria andFtNotIn(List<String> values) {
            addCriterion("ft not in", values, "ft");
            return (Criteria) this;
        }

        public Criteria andFtBetween(String value1, String value2) {
            addCriterion("ft between", value1, value2, "ft");
            return (Criteria) this;
        }

        public Criteria andFtNotBetween(String value1, String value2) {
            addCriterion("ft not between", value1, value2, "ft");
            return (Criteria) this;
        }

        public Criteria andZyIsNull() {
            addCriterion("zy is null");
            return (Criteria) this;
        }

        public Criteria andZyIsNotNull() {
            addCriterion("zy is not null");
            return (Criteria) this;
        }

        public Criteria andZyEqualTo(String value) {
            addCriterion("zy =", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotEqualTo(String value) {
            addCriterion("zy <>", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyGreaterThan(String value) {
            addCriterion("zy >", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyGreaterThanOrEqualTo(String value) {
            addCriterion("zy >=", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyLessThan(String value) {
            addCriterion("zy <", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyLessThanOrEqualTo(String value) {
            addCriterion("zy <=", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyLike(String value) {
            addCriterion("zy like", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotLike(String value) {
            addCriterion("zy not like", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyIn(List<String> values) {
            addCriterion("zy in", values, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotIn(List<String> values) {
            addCriterion("zy not in", values, "zy");
            return (Criteria) this;
        }

        public Criteria andZyBetween(String value1, String value2) {
            addCriterion("zy between", value1, value2, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotBetween(String value1, String value2) {
            addCriterion("zy not between", value1, value2, "zy");
            return (Criteria) this;
        }

        public Criteria andCgIsNull() {
            addCriterion("cg is null");
            return (Criteria) this;
        }

        public Criteria andCgIsNotNull() {
            addCriterion("cg is not null");
            return (Criteria) this;
        }

        public Criteria andCgEqualTo(String value) {
            addCriterion("cg =", value, "cg");
            return (Criteria) this;
        }

        public Criteria andCgNotEqualTo(String value) {
            addCriterion("cg <>", value, "cg");
            return (Criteria) this;
        }

        public Criteria andCgGreaterThan(String value) {
            addCriterion("cg >", value, "cg");
            return (Criteria) this;
        }

        public Criteria andCgGreaterThanOrEqualTo(String value) {
            addCriterion("cg >=", value, "cg");
            return (Criteria) this;
        }

        public Criteria andCgLessThan(String value) {
            addCriterion("cg <", value, "cg");
            return (Criteria) this;
        }

        public Criteria andCgLessThanOrEqualTo(String value) {
            addCriterion("cg <=", value, "cg");
            return (Criteria) this;
        }

        public Criteria andCgLike(String value) {
            addCriterion("cg like", value, "cg");
            return (Criteria) this;
        }

        public Criteria andCgNotLike(String value) {
            addCriterion("cg not like", value, "cg");
            return (Criteria) this;
        }

        public Criteria andCgIn(List<String> values) {
            addCriterion("cg in", values, "cg");
            return (Criteria) this;
        }

        public Criteria andCgNotIn(List<String> values) {
            addCriterion("cg not in", values, "cg");
            return (Criteria) this;
        }

        public Criteria andCgBetween(String value1, String value2) {
            addCriterion("cg between", value1, value2, "cg");
            return (Criteria) this;
        }

        public Criteria andCgNotBetween(String value1, String value2) {
            addCriterion("cg not between", value1, value2, "cg");
            return (Criteria) this;
        }

        public Criteria andCxIsNull() {
            addCriterion("cx is null");
            return (Criteria) this;
        }

        public Criteria andCxIsNotNull() {
            addCriterion("cx is not null");
            return (Criteria) this;
        }

        public Criteria andCxEqualTo(String value) {
            addCriterion("cx =", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxNotEqualTo(String value) {
            addCriterion("cx <>", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxGreaterThan(String value) {
            addCriterion("cx >", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxGreaterThanOrEqualTo(String value) {
            addCriterion("cx >=", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxLessThan(String value) {
            addCriterion("cx <", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxLessThanOrEqualTo(String value) {
            addCriterion("cx <=", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxLike(String value) {
            addCriterion("cx like", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxNotLike(String value) {
            addCriterion("cx not like", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxIn(List<String> values) {
            addCriterion("cx in", values, "cx");
            return (Criteria) this;
        }

        public Criteria andCxNotIn(List<String> values) {
            addCriterion("cx not in", values, "cx");
            return (Criteria) this;
        }

        public Criteria andCxBetween(String value1, String value2) {
            addCriterion("cx between", value1, value2, "cx");
            return (Criteria) this;
        }

        public Criteria andCxNotBetween(String value1, String value2) {
            addCriterion("cx not between", value1, value2, "cx");
            return (Criteria) this;
        }

        public Criteria andJwIsNull() {
            addCriterion("jw is null");
            return (Criteria) this;
        }

        public Criteria andJwIsNotNull() {
            addCriterion("jw is not null");
            return (Criteria) this;
        }

        public Criteria andJwEqualTo(String value) {
            addCriterion("jw =", value, "jw");
            return (Criteria) this;
        }

        public Criteria andJwNotEqualTo(String value) {
            addCriterion("jw <>", value, "jw");
            return (Criteria) this;
        }

        public Criteria andJwGreaterThan(String value) {
            addCriterion("jw >", value, "jw");
            return (Criteria) this;
        }

        public Criteria andJwGreaterThanOrEqualTo(String value) {
            addCriterion("jw >=", value, "jw");
            return (Criteria) this;
        }

        public Criteria andJwLessThan(String value) {
            addCriterion("jw <", value, "jw");
            return (Criteria) this;
        }

        public Criteria andJwLessThanOrEqualTo(String value) {
            addCriterion("jw <=", value, "jw");
            return (Criteria) this;
        }

        public Criteria andJwLike(String value) {
            addCriterion("jw like", value, "jw");
            return (Criteria) this;
        }

        public Criteria andJwNotLike(String value) {
            addCriterion("jw not like", value, "jw");
            return (Criteria) this;
        }

        public Criteria andJwIn(List<String> values) {
            addCriterion("jw in", values, "jw");
            return (Criteria) this;
        }

        public Criteria andJwNotIn(List<String> values) {
            addCriterion("jw not in", values, "jw");
            return (Criteria) this;
        }

        public Criteria andJwBetween(String value1, String value2) {
            addCriterion("jw between", value1, value2, "jw");
            return (Criteria) this;
        }

        public Criteria andJwNotBetween(String value1, String value2) {
            addCriterion("jw not between", value1, value2, "jw");
            return (Criteria) this;
        }

        public Criteria andZxIsNull() {
            addCriterion("zx is null");
            return (Criteria) this;
        }

        public Criteria andZxIsNotNull() {
            addCriterion("zx is not null");
            return (Criteria) this;
        }

        public Criteria andZxEqualTo(String value) {
            addCriterion("zx =", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxNotEqualTo(String value) {
            addCriterion("zx <>", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxGreaterThan(String value) {
            addCriterion("zx >", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxGreaterThanOrEqualTo(String value) {
            addCriterion("zx >=", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxLessThan(String value) {
            addCriterion("zx <", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxLessThanOrEqualTo(String value) {
            addCriterion("zx <=", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxLike(String value) {
            addCriterion("zx like", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxNotLike(String value) {
            addCriterion("zx not like", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxIn(List<String> values) {
            addCriterion("zx in", values, "zx");
            return (Criteria) this;
        }

        public Criteria andZxNotIn(List<String> values) {
            addCriterion("zx not in", values, "zx");
            return (Criteria) this;
        }

        public Criteria andZxBetween(String value1, String value2) {
            addCriterion("zx between", value1, value2, "zx");
            return (Criteria) this;
        }

        public Criteria andZxNotBetween(String value1, String value2) {
            addCriterion("zx not between", value1, value2, "zx");
            return (Criteria) this;
        }

        public Criteria andPmIsNull() {
            addCriterion("pm is null");
            return (Criteria) this;
        }

        public Criteria andPmIsNotNull() {
            addCriterion("pm is not null");
            return (Criteria) this;
        }

        public Criteria andPmEqualTo(String value) {
            addCriterion("pm =", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmNotEqualTo(String value) {
            addCriterion("pm <>", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmGreaterThan(String value) {
            addCriterion("pm >", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmGreaterThanOrEqualTo(String value) {
            addCriterion("pm >=", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmLessThan(String value) {
            addCriterion("pm <", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmLessThanOrEqualTo(String value) {
            addCriterion("pm <=", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmLike(String value) {
            addCriterion("pm like", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmNotLike(String value) {
            addCriterion("pm not like", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmIn(List<String> values) {
            addCriterion("pm in", values, "pm");
            return (Criteria) this;
        }

        public Criteria andPmNotIn(List<String> values) {
            addCriterion("pm not in", values, "pm");
            return (Criteria) this;
        }

        public Criteria andPmBetween(String value1, String value2) {
            addCriterion("pm between", value1, value2, "pm");
            return (Criteria) this;
        }

        public Criteria andPmNotBetween(String value1, String value2) {
            addCriterion("pm not between", value1, value2, "pm");
            return (Criteria) this;
        }

        public Criteria andWgIsNull() {
            addCriterion("wg is null");
            return (Criteria) this;
        }

        public Criteria andWgIsNotNull() {
            addCriterion("wg is not null");
            return (Criteria) this;
        }

        public Criteria andWgEqualTo(String value) {
            addCriterion("wg =", value, "wg");
            return (Criteria) this;
        }

        public Criteria andWgNotEqualTo(String value) {
            addCriterion("wg <>", value, "wg");
            return (Criteria) this;
        }

        public Criteria andWgGreaterThan(String value) {
            addCriterion("wg >", value, "wg");
            return (Criteria) this;
        }

        public Criteria andWgGreaterThanOrEqualTo(String value) {
            addCriterion("wg >=", value, "wg");
            return (Criteria) this;
        }

        public Criteria andWgLessThan(String value) {
            addCriterion("wg <", value, "wg");
            return (Criteria) this;
        }

        public Criteria andWgLessThanOrEqualTo(String value) {
            addCriterion("wg <=", value, "wg");
            return (Criteria) this;
        }

        public Criteria andWgLike(String value) {
            addCriterion("wg like", value, "wg");
            return (Criteria) this;
        }

        public Criteria andWgNotLike(String value) {
            addCriterion("wg not like", value, "wg");
            return (Criteria) this;
        }

        public Criteria andWgIn(List<String> values) {
            addCriterion("wg in", values, "wg");
            return (Criteria) this;
        }

        public Criteria andWgNotIn(List<String> values) {
            addCriterion("wg not in", values, "wg");
            return (Criteria) this;
        }

        public Criteria andWgBetween(String value1, String value2) {
            addCriterion("wg between", value1, value2, "wg");
            return (Criteria) this;
        }

        public Criteria andWgNotBetween(String value1, String value2) {
            addCriterion("wg not between", value1, value2, "wg");
            return (Criteria) this;
        }

        public Criteria andDtIsNull() {
            addCriterion("dt is null");
            return (Criteria) this;
        }

        public Criteria andDtIsNotNull() {
            addCriterion("dt is not null");
            return (Criteria) this;
        }

        public Criteria andDtEqualTo(String value) {
            addCriterion("dt =", value, "dt");
            return (Criteria) this;
        }

        public Criteria andDtNotEqualTo(String value) {
            addCriterion("dt <>", value, "dt");
            return (Criteria) this;
        }

        public Criteria andDtGreaterThan(String value) {
            addCriterion("dt >", value, "dt");
            return (Criteria) this;
        }

        public Criteria andDtGreaterThanOrEqualTo(String value) {
            addCriterion("dt >=", value, "dt");
            return (Criteria) this;
        }

        public Criteria andDtLessThan(String value) {
            addCriterion("dt <", value, "dt");
            return (Criteria) this;
        }

        public Criteria andDtLessThanOrEqualTo(String value) {
            addCriterion("dt <=", value, "dt");
            return (Criteria) this;
        }

        public Criteria andDtLike(String value) {
            addCriterion("dt like", value, "dt");
            return (Criteria) this;
        }

        public Criteria andDtNotLike(String value) {
            addCriterion("dt not like", value, "dt");
            return (Criteria) this;
        }

        public Criteria andDtIn(List<String> values) {
            addCriterion("dt in", values, "dt");
            return (Criteria) this;
        }

        public Criteria andDtNotIn(List<String> values) {
            addCriterion("dt not in", values, "dt");
            return (Criteria) this;
        }

        public Criteria andDtBetween(String value1, String value2) {
            addCriterion("dt between", value1, value2, "dt");
            return (Criteria) this;
        }

        public Criteria andDtNotBetween(String value1, String value2) {
            addCriterion("dt not between", value1, value2, "dt");
            return (Criteria) this;
        }

        public Criteria andJtIsNull() {
            addCriterion("jt is null");
            return (Criteria) this;
        }

        public Criteria andJtIsNotNull() {
            addCriterion("jt is not null");
            return (Criteria) this;
        }

        public Criteria andJtEqualTo(String value) {
            addCriterion("jt =", value, "jt");
            return (Criteria) this;
        }

        public Criteria andJtNotEqualTo(String value) {
            addCriterion("jt <>", value, "jt");
            return (Criteria) this;
        }

        public Criteria andJtGreaterThan(String value) {
            addCriterion("jt >", value, "jt");
            return (Criteria) this;
        }

        public Criteria andJtGreaterThanOrEqualTo(String value) {
            addCriterion("jt >=", value, "jt");
            return (Criteria) this;
        }

        public Criteria andJtLessThan(String value) {
            addCriterion("jt <", value, "jt");
            return (Criteria) this;
        }

        public Criteria andJtLessThanOrEqualTo(String value) {
            addCriterion("jt <=", value, "jt");
            return (Criteria) this;
        }

        public Criteria andJtLike(String value) {
            addCriterion("jt like", value, "jt");
            return (Criteria) this;
        }

        public Criteria andJtNotLike(String value) {
            addCriterion("jt not like", value, "jt");
            return (Criteria) this;
        }

        public Criteria andJtIn(List<String> values) {
            addCriterion("jt in", values, "jt");
            return (Criteria) this;
        }

        public Criteria andJtNotIn(List<String> values) {
            addCriterion("jt not in", values, "jt");
            return (Criteria) this;
        }

        public Criteria andJtBetween(String value1, String value2) {
            addCriterion("jt between", value1, value2, "jt");
            return (Criteria) this;
        }

        public Criteria andJtNotBetween(String value1, String value2) {
            addCriterion("jt not between", value1, value2, "jt");
            return (Criteria) this;
        }

        public Criteria andLyhjIsNull() {
            addCriterion("lyhj is null");
            return (Criteria) this;
        }

        public Criteria andLyhjIsNotNull() {
            addCriterion("lyhj is not null");
            return (Criteria) this;
        }

        public Criteria andLyhjEqualTo(String value) {
            addCriterion("lyhj =", value, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjNotEqualTo(String value) {
            addCriterion("lyhj <>", value, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjGreaterThan(String value) {
            addCriterion("lyhj >", value, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjGreaterThanOrEqualTo(String value) {
            addCriterion("lyhj >=", value, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjLessThan(String value) {
            addCriterion("lyhj <", value, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjLessThanOrEqualTo(String value) {
            addCriterion("lyhj <=", value, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjLike(String value) {
            addCriterion("lyhj like", value, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjNotLike(String value) {
            addCriterion("lyhj not like", value, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjIn(List<String> values) {
            addCriterion("lyhj in", values, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjNotIn(List<String> values) {
            addCriterion("lyhj not in", values, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjBetween(String value1, String value2) {
            addCriterion("lyhj between", value1, value2, "lyhj");
            return (Criteria) this;
        }

        public Criteria andLyhjNotBetween(String value1, String value2) {
            addCriterion("lyhj not between", value1, value2, "lyhj");
            return (Criteria) this;
        }

        public Criteria andGgIsNull() {
            addCriterion("gg is null");
            return (Criteria) this;
        }

        public Criteria andGgIsNotNull() {
            addCriterion("gg is not null");
            return (Criteria) this;
        }

        public Criteria andGgEqualTo(String value) {
            addCriterion("gg =", value, "gg");
            return (Criteria) this;
        }

        public Criteria andGgNotEqualTo(String value) {
            addCriterion("gg <>", value, "gg");
            return (Criteria) this;
        }

        public Criteria andGgGreaterThan(String value) {
            addCriterion("gg >", value, "gg");
            return (Criteria) this;
        }

        public Criteria andGgGreaterThanOrEqualTo(String value) {
            addCriterion("gg >=", value, "gg");
            return (Criteria) this;
        }

        public Criteria andGgLessThan(String value) {
            addCriterion("gg <", value, "gg");
            return (Criteria) this;
        }

        public Criteria andGgLessThanOrEqualTo(String value) {
            addCriterion("gg <=", value, "gg");
            return (Criteria) this;
        }

        public Criteria andGgLike(String value) {
            addCriterion("gg like", value, "gg");
            return (Criteria) this;
        }

        public Criteria andGgNotLike(String value) {
            addCriterion("gg not like", value, "gg");
            return (Criteria) this;
        }

        public Criteria andGgIn(List<String> values) {
            addCriterion("gg in", values, "gg");
            return (Criteria) this;
        }

        public Criteria andGgNotIn(List<String> values) {
            addCriterion("gg not in", values, "gg");
            return (Criteria) this;
        }

        public Criteria andGgBetween(String value1, String value2) {
            addCriterion("gg between", value1, value2, "gg");
            return (Criteria) this;
        }

        public Criteria andGgNotBetween(String value1, String value2) {
            addCriterion("gg not between", value1, value2, "gg");
            return (Criteria) this;
        }

        public Criteria andWqIsNull() {
            addCriterion("wq is null");
            return (Criteria) this;
        }

        public Criteria andWqIsNotNull() {
            addCriterion("wq is not null");
            return (Criteria) this;
        }

        public Criteria andWqEqualTo(String value) {
            addCriterion("wq =", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqNotEqualTo(String value) {
            addCriterion("wq <>", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqGreaterThan(String value) {
            addCriterion("wq >", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqGreaterThanOrEqualTo(String value) {
            addCriterion("wq >=", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqLessThan(String value) {
            addCriterion("wq <", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqLessThanOrEqualTo(String value) {
            addCriterion("wq <=", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqLike(String value) {
            addCriterion("wq like", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqNotLike(String value) {
            addCriterion("wq not like", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqIn(List<String> values) {
            addCriterion("wq in", values, "wq");
            return (Criteria) this;
        }

        public Criteria andWqNotIn(List<String> values) {
            addCriterion("wq not in", values, "wq");
            return (Criteria) this;
        }

        public Criteria andWqBetween(String value1, String value2) {
            addCriterion("wq between", value1, value2, "wq");
            return (Criteria) this;
        }

        public Criteria andWqNotBetween(String value1, String value2) {
            addCriterion("wq not between", value1, value2, "wq");
            return (Criteria) this;
        }

        public Criteria andNqIsNull() {
            addCriterion("nq is null");
            return (Criteria) this;
        }

        public Criteria andNqIsNotNull() {
            addCriterion("nq is not null");
            return (Criteria) this;
        }

        public Criteria andNqEqualTo(String value) {
            addCriterion("nq =", value, "nq");
            return (Criteria) this;
        }

        public Criteria andNqNotEqualTo(String value) {
            addCriterion("nq <>", value, "nq");
            return (Criteria) this;
        }

        public Criteria andNqGreaterThan(String value) {
            addCriterion("nq >", value, "nq");
            return (Criteria) this;
        }

        public Criteria andNqGreaterThanOrEqualTo(String value) {
            addCriterion("nq >=", value, "nq");
            return (Criteria) this;
        }

        public Criteria andNqLessThan(String value) {
            addCriterion("nq <", value, "nq");
            return (Criteria) this;
        }

        public Criteria andNqLessThanOrEqualTo(String value) {
            addCriterion("nq <=", value, "nq");
            return (Criteria) this;
        }

        public Criteria andNqLike(String value) {
            addCriterion("nq like", value, "nq");
            return (Criteria) this;
        }

        public Criteria andNqNotLike(String value) {
            addCriterion("nq not like", value, "nq");
            return (Criteria) this;
        }

        public Criteria andNqIn(List<String> values) {
            addCriterion("nq in", values, "nq");
            return (Criteria) this;
        }

        public Criteria andNqNotIn(List<String> values) {
            addCriterion("nq not in", values, "nq");
            return (Criteria) this;
        }

        public Criteria andNqBetween(String value1, String value2) {
            addCriterion("nq between", value1, value2, "nq");
            return (Criteria) this;
        }

        public Criteria andNqNotBetween(String value1, String value2) {
            addCriterion("nq not between", value1, value2, "nq");
            return (Criteria) this;
        }

        public Criteria andDmIsNull() {
            addCriterion("dm is null");
            return (Criteria) this;
        }

        public Criteria andDmIsNotNull() {
            addCriterion("dm is not null");
            return (Criteria) this;
        }

        public Criteria andDmEqualTo(String value) {
            addCriterion("dm =", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmNotEqualTo(String value) {
            addCriterion("dm <>", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmGreaterThan(String value) {
            addCriterion("dm >", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmGreaterThanOrEqualTo(String value) {
            addCriterion("dm >=", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmLessThan(String value) {
            addCriterion("dm <", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmLessThanOrEqualTo(String value) {
            addCriterion("dm <=", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmLike(String value) {
            addCriterion("dm like", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmNotLike(String value) {
            addCriterion("dm not like", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmIn(List<String> values) {
            addCriterion("dm in", values, "dm");
            return (Criteria) this;
        }

        public Criteria andDmNotIn(List<String> values) {
            addCriterion("dm not in", values, "dm");
            return (Criteria) this;
        }

        public Criteria andDmBetween(String value1, String value2) {
            addCriterion("dm between", value1, value2, "dm");
            return (Criteria) this;
        }

        public Criteria andDmNotBetween(String value1, String value2) {
            addCriterion("dm not between", value1, value2, "dm");
            return (Criteria) this;
        }

        public Criteria andThbIsNull() {
            addCriterion("thb is null");
            return (Criteria) this;
        }

        public Criteria andThbIsNotNull() {
            addCriterion("thb is not null");
            return (Criteria) this;
        }

        public Criteria andThbEqualTo(String value) {
            addCriterion("thb =", value, "thb");
            return (Criteria) this;
        }

        public Criteria andThbNotEqualTo(String value) {
            addCriterion("thb <>", value, "thb");
            return (Criteria) this;
        }

        public Criteria andThbGreaterThan(String value) {
            addCriterion("thb >", value, "thb");
            return (Criteria) this;
        }

        public Criteria andThbGreaterThanOrEqualTo(String value) {
            addCriterion("thb >=", value, "thb");
            return (Criteria) this;
        }

        public Criteria andThbLessThan(String value) {
            addCriterion("thb <", value, "thb");
            return (Criteria) this;
        }

        public Criteria andThbLessThanOrEqualTo(String value) {
            addCriterion("thb <=", value, "thb");
            return (Criteria) this;
        }

        public Criteria andThbLike(String value) {
            addCriterion("thb like", value, "thb");
            return (Criteria) this;
        }

        public Criteria andThbNotLike(String value) {
            addCriterion("thb not like", value, "thb");
            return (Criteria) this;
        }

        public Criteria andThbIn(List<String> values) {
            addCriterion("thb in", values, "thb");
            return (Criteria) this;
        }

        public Criteria andThbNotIn(List<String> values) {
            addCriterion("thb not in", values, "thb");
            return (Criteria) this;
        }

        public Criteria andThbBetween(String value1, String value2) {
            addCriterion("thb between", value1, value2, "thb");
            return (Criteria) this;
        }

        public Criteria andThbNotBetween(String value1, String value2) {
            addCriterion("thb not between", value1, value2, "thb");
            return (Criteria) this;
        }

        public Criteria andMcIsNull() {
            addCriterion("mc is null");
            return (Criteria) this;
        }

        public Criteria andMcIsNotNull() {
            addCriterion("mc is not null");
            return (Criteria) this;
        }

        public Criteria andMcEqualTo(String value) {
            addCriterion("mc =", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotEqualTo(String value) {
            addCriterion("mc <>", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcGreaterThan(String value) {
            addCriterion("mc >", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcGreaterThanOrEqualTo(String value) {
            addCriterion("mc >=", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcLessThan(String value) {
            addCriterion("mc <", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcLessThanOrEqualTo(String value) {
            addCriterion("mc <=", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcLike(String value) {
            addCriterion("mc like", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotLike(String value) {
            addCriterion("mc not like", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcIn(List<String> values) {
            addCriterion("mc in", values, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotIn(List<String> values) {
            addCriterion("mc not in", values, "mc");
            return (Criteria) this;
        }

        public Criteria andMcBetween(String value1, String value2) {
            addCriterion("mc between", value1, value2, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotBetween(String value1, String value2) {
            addCriterion("mc not between", value1, value2, "mc");
            return (Criteria) this;
        }

        public Criteria andWsjIsNull() {
            addCriterion("wsj is null");
            return (Criteria) this;
        }

        public Criteria andWsjIsNotNull() {
            addCriterion("wsj is not null");
            return (Criteria) this;
        }

        public Criteria andWsjEqualTo(String value) {
            addCriterion("wsj =", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjNotEqualTo(String value) {
            addCriterion("wsj <>", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjGreaterThan(String value) {
            addCriterion("wsj >", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjGreaterThanOrEqualTo(String value) {
            addCriterion("wsj >=", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjLessThan(String value) {
            addCriterion("wsj <", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjLessThanOrEqualTo(String value) {
            addCriterion("wsj <=", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjLike(String value) {
            addCriterion("wsj like", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjNotLike(String value) {
            addCriterion("wsj not like", value, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjIn(List<String> values) {
            addCriterion("wsj in", values, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjNotIn(List<String> values) {
            addCriterion("wsj not in", values, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjBetween(String value1, String value2) {
            addCriterion("wsj between", value1, value2, "wsj");
            return (Criteria) this;
        }

        public Criteria andWsjNotBetween(String value1, String value2) {
            addCriterion("wsj not between", value1, value2, "wsj");
            return (Criteria) this;
        }

        public Criteria andLtjIsNull() {
            addCriterion("ltj is null");
            return (Criteria) this;
        }

        public Criteria andLtjIsNotNull() {
            addCriterion("ltj is not null");
            return (Criteria) this;
        }

        public Criteria andLtjEqualTo(String value) {
            addCriterion("ltj =", value, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjNotEqualTo(String value) {
            addCriterion("ltj <>", value, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjGreaterThan(String value) {
            addCriterion("ltj >", value, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjGreaterThanOrEqualTo(String value) {
            addCriterion("ltj >=", value, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjLessThan(String value) {
            addCriterion("ltj <", value, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjLessThanOrEqualTo(String value) {
            addCriterion("ltj <=", value, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjLike(String value) {
            addCriterion("ltj like", value, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjNotLike(String value) {
            addCriterion("ltj not like", value, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjIn(List<String> values) {
            addCriterion("ltj in", values, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjNotIn(List<String> values) {
            addCriterion("ltj not in", values, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjBetween(String value1, String value2) {
            addCriterion("ltj between", value1, value2, "ltj");
            return (Criteria) this;
        }

        public Criteria andLtjNotBetween(String value1, String value2) {
            addCriterion("ltj not between", value1, value2, "ltj");
            return (Criteria) this;
        }

        public Criteria andSsIsNull() {
            addCriterion("ss is null");
            return (Criteria) this;
        }

        public Criteria andSsIsNotNull() {
            addCriterion("ss is not null");
            return (Criteria) this;
        }

        public Criteria andSsEqualTo(String value) {
            addCriterion("ss =", value, "ss");
            return (Criteria) this;
        }

        public Criteria andSsNotEqualTo(String value) {
            addCriterion("ss <>", value, "ss");
            return (Criteria) this;
        }

        public Criteria andSsGreaterThan(String value) {
            addCriterion("ss >", value, "ss");
            return (Criteria) this;
        }

        public Criteria andSsGreaterThanOrEqualTo(String value) {
            addCriterion("ss >=", value, "ss");
            return (Criteria) this;
        }

        public Criteria andSsLessThan(String value) {
            addCriterion("ss <", value, "ss");
            return (Criteria) this;
        }

        public Criteria andSsLessThanOrEqualTo(String value) {
            addCriterion("ss <=", value, "ss");
            return (Criteria) this;
        }

        public Criteria andSsLike(String value) {
            addCriterion("ss like", value, "ss");
            return (Criteria) this;
        }

        public Criteria andSsNotLike(String value) {
            addCriterion("ss not like", value, "ss");
            return (Criteria) this;
        }

        public Criteria andSsIn(List<String> values) {
            addCriterion("ss in", values, "ss");
            return (Criteria) this;
        }

        public Criteria andSsNotIn(List<String> values) {
            addCriterion("ss not in", values, "ss");
            return (Criteria) this;
        }

        public Criteria andSsBetween(String value1, String value2) {
            addCriterion("ss between", value1, value2, "ss");
            return (Criteria) this;
        }

        public Criteria andSsNotBetween(String value1, String value2) {
            addCriterion("ss not between", value1, value2, "ss");
            return (Criteria) this;
        }

        public Criteria andBxfxIsNull() {
            addCriterion("bxfx is null");
            return (Criteria) this;
        }

        public Criteria andBxfxIsNotNull() {
            addCriterion("bxfx is not null");
            return (Criteria) this;
        }

        public Criteria andBxfxEqualTo(String value) {
            addCriterion("bxfx =", value, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxNotEqualTo(String value) {
            addCriterion("bxfx <>", value, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxGreaterThan(String value) {
            addCriterion("bxfx >", value, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxGreaterThanOrEqualTo(String value) {
            addCriterion("bxfx >=", value, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxLessThan(String value) {
            addCriterion("bxfx <", value, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxLessThanOrEqualTo(String value) {
            addCriterion("bxfx <=", value, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxLike(String value) {
            addCriterion("bxfx like", value, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxNotLike(String value) {
            addCriterion("bxfx not like", value, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxIn(List<String> values) {
            addCriterion("bxfx in", values, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxNotIn(List<String> values) {
            addCriterion("bxfx not in", values, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxBetween(String value1, String value2) {
            addCriterion("bxfx between", value1, value2, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBxfxNotBetween(String value1, String value2) {
            addCriterion("bxfx not between", value1, value2, "bxfx");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("bz is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("bz is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("bz =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("bz <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("bz >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("bz >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("bz <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("bz <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("bz like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("bz not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("bz in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("bz not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("bz between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("bz not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzreportIsNull() {
            addCriterion("bzReport is null");
            return (Criteria) this;
        }

        public Criteria andBzreportIsNotNull() {
            addCriterion("bzReport is not null");
            return (Criteria) this;
        }

        public Criteria andBzreportEqualTo(String value) {
            addCriterion("bzReport =", value, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportNotEqualTo(String value) {
            addCriterion("bzReport <>", value, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportGreaterThan(String value) {
            addCriterion("bzReport >", value, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportGreaterThanOrEqualTo(String value) {
            addCriterion("bzReport >=", value, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportLessThan(String value) {
            addCriterion("bzReport <", value, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportLessThanOrEqualTo(String value) {
            addCriterion("bzReport <=", value, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportLike(String value) {
            addCriterion("bzReport like", value, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportNotLike(String value) {
            addCriterion("bzReport not like", value, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportIn(List<String> values) {
            addCriterion("bzReport in", values, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportNotIn(List<String> values) {
            addCriterion("bzReport not in", values, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportBetween(String value1, String value2) {
            addCriterion("bzReport between", value1, value2, "bzreport");
            return (Criteria) this;
        }

        public Criteria andBzreportNotBetween(String value1, String value2) {
            addCriterion("bzReport not between", value1, value2, "bzreport");
            return (Criteria) this;
        }

        public Criteria andDefineddata1IsNull() {
            addCriterion("DefinedData1 is null");
            return (Criteria) this;
        }

        public Criteria andDefineddata1IsNotNull() {
            addCriterion("DefinedData1 is not null");
            return (Criteria) this;
        }

        public Criteria andDefineddata1EqualTo(String value) {
            addCriterion("DefinedData1 =", value, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1NotEqualTo(String value) {
            addCriterion("DefinedData1 <>", value, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1GreaterThan(String value) {
            addCriterion("DefinedData1 >", value, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1GreaterThanOrEqualTo(String value) {
            addCriterion("DefinedData1 >=", value, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1LessThan(String value) {
            addCriterion("DefinedData1 <", value, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1LessThanOrEqualTo(String value) {
            addCriterion("DefinedData1 <=", value, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1Like(String value) {
            addCriterion("DefinedData1 like", value, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1NotLike(String value) {
            addCriterion("DefinedData1 not like", value, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1In(List<String> values) {
            addCriterion("DefinedData1 in", values, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1NotIn(List<String> values) {
            addCriterion("DefinedData1 not in", values, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1Between(String value1, String value2) {
            addCriterion("DefinedData1 between", value1, value2, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata1NotBetween(String value1, String value2) {
            addCriterion("DefinedData1 not between", value1, value2, "defineddata1");
            return (Criteria) this;
        }

        public Criteria andDefineddata2IsNull() {
            addCriterion("DefinedData2 is null");
            return (Criteria) this;
        }

        public Criteria andDefineddata2IsNotNull() {
            addCriterion("DefinedData2 is not null");
            return (Criteria) this;
        }

        public Criteria andDefineddata2EqualTo(String value) {
            addCriterion("DefinedData2 =", value, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2NotEqualTo(String value) {
            addCriterion("DefinedData2 <>", value, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2GreaterThan(String value) {
            addCriterion("DefinedData2 >", value, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2GreaterThanOrEqualTo(String value) {
            addCriterion("DefinedData2 >=", value, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2LessThan(String value) {
            addCriterion("DefinedData2 <", value, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2LessThanOrEqualTo(String value) {
            addCriterion("DefinedData2 <=", value, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2Like(String value) {
            addCriterion("DefinedData2 like", value, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2NotLike(String value) {
            addCriterion("DefinedData2 not like", value, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2In(List<String> values) {
            addCriterion("DefinedData2 in", values, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2NotIn(List<String> values) {
            addCriterion("DefinedData2 not in", values, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2Between(String value1, String value2) {
            addCriterion("DefinedData2 between", value1, value2, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata2NotBetween(String value1, String value2) {
            addCriterion("DefinedData2 not between", value1, value2, "defineddata2");
            return (Criteria) this;
        }

        public Criteria andDefineddata3IsNull() {
            addCriterion("DefinedData3 is null");
            return (Criteria) this;
        }

        public Criteria andDefineddata3IsNotNull() {
            addCriterion("DefinedData3 is not null");
            return (Criteria) this;
        }

        public Criteria andDefineddata3EqualTo(String value) {
            addCriterion("DefinedData3 =", value, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3NotEqualTo(String value) {
            addCriterion("DefinedData3 <>", value, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3GreaterThan(String value) {
            addCriterion("DefinedData3 >", value, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3GreaterThanOrEqualTo(String value) {
            addCriterion("DefinedData3 >=", value, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3LessThan(String value) {
            addCriterion("DefinedData3 <", value, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3LessThanOrEqualTo(String value) {
            addCriterion("DefinedData3 <=", value, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3Like(String value) {
            addCriterion("DefinedData3 like", value, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3NotLike(String value) {
            addCriterion("DefinedData3 not like", value, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3In(List<String> values) {
            addCriterion("DefinedData3 in", values, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3NotIn(List<String> values) {
            addCriterion("DefinedData3 not in", values, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3Between(String value1, String value2) {
            addCriterion("DefinedData3 between", value1, value2, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andDefineddata3NotBetween(String value1, String value2) {
            addCriterion("DefinedData3 not between", value1, value2, "defineddata3");
            return (Criteria) this;
        }

        public Criteria andXmldataIsNull() {
            addCriterion("XmlData is null");
            return (Criteria) this;
        }

        public Criteria andXmldataIsNotNull() {
            addCriterion("XmlData is not null");
            return (Criteria) this;
        }

        public Criteria andXmldataEqualTo(String value) {
            addCriterion("XmlData =", value, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataNotEqualTo(String value) {
            addCriterion("XmlData <>", value, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataGreaterThan(String value) {
            addCriterion("XmlData >", value, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataGreaterThanOrEqualTo(String value) {
            addCriterion("XmlData >=", value, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataLessThan(String value) {
            addCriterion("XmlData <", value, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataLessThanOrEqualTo(String value) {
            addCriterion("XmlData <=", value, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataLike(String value) {
            addCriterion("XmlData like", value, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataNotLike(String value) {
            addCriterion("XmlData not like", value, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataIn(List<String> values) {
            addCriterion("XmlData in", values, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataNotIn(List<String> values) {
            addCriterion("XmlData not in", values, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataBetween(String value1, String value2) {
            addCriterion("XmlData between", value1, value2, "xmldata");
            return (Criteria) this;
        }

        public Criteria andXmldataNotBetween(String value1, String value2) {
            addCriterion("XmlData not between", value1, value2, "xmldata");
            return (Criteria) this;
        }

        public Criteria andPmStructureIsNull() {
            addCriterion("Pm_Structure is null");
            return (Criteria) this;
        }

        public Criteria andPmStructureIsNotNull() {
            addCriterion("Pm_Structure is not null");
            return (Criteria) this;
        }

        public Criteria andPmStructureEqualTo(String value) {
            addCriterion("Pm_Structure =", value, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureNotEqualTo(String value) {
            addCriterion("Pm_Structure <>", value, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureGreaterThan(String value) {
            addCriterion("Pm_Structure >", value, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureGreaterThanOrEqualTo(String value) {
            addCriterion("Pm_Structure >=", value, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureLessThan(String value) {
            addCriterion("Pm_Structure <", value, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureLessThanOrEqualTo(String value) {
            addCriterion("Pm_Structure <=", value, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureLike(String value) {
            addCriterion("Pm_Structure like", value, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureNotLike(String value) {
            addCriterion("Pm_Structure not like", value, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureIn(List<String> values) {
            addCriterion("Pm_Structure in", values, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureNotIn(List<String> values) {
            addCriterion("Pm_Structure not in", values, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureBetween(String value1, String value2) {
            addCriterion("Pm_Structure between", value1, value2, "pmStructure");
            return (Criteria) this;
        }

        public Criteria andPmStructureNotBetween(String value1, String value2) {
            addCriterion("Pm_Structure not between", value1, value2, "pmStructure");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 10 21:28:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UDS_HOURSE
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}