package com.spring.mpvue.springbootmpvue.sqlserver.po;

public class UdsHourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.REALESTATEID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer realestateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.build
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String build;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.name
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.tdsy
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String tdsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.cb
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String cb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.jg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.zcs
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String zcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.pgc
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String pgc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.dh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.tn
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String tn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.ft
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String ft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.zy
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String zy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.cg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String cg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.cx
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String cx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.jw
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String jw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.zx
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String zx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.pm
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String pm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.wg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String wg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.dt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String dt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.jt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String jt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.lyhj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String lyhj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.gg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.wq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String wq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.nq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String nq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.dm
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String dm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.thb
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String thb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.mc
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.wsj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String wsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.ltj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String ltj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.ss
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String ss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.bxfx
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String bxfx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.bz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.bzReport
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String bzreport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.DefinedData1
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String defineddata1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.DefinedData2
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String defineddata2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.DefinedData3
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String defineddata3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.XmlData
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String xmldata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_HOURSE.Pm_Structure
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String pmStructure;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.ID
     *
     * @return the value of UDS_HOURSE.ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.ID
     *
     * @param id the value for UDS_HOURSE.ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.REALESTATEID
     *
     * @return the value of UDS_HOURSE.REALESTATEID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getRealestateid() {
        return realestateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.REALESTATEID
     *
     * @param realestateid the value for UDS_HOURSE.REALESTATEID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRealestateid(Integer realestateid) {
        this.realestateid = realestateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.build
     *
     * @return the value of UDS_HOURSE.build
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getBuild() {
        return build;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.build
     *
     * @param build the value for UDS_HOURSE.build
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBuild(String build) {
        this.build = build == null ? null : build.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.name
     *
     * @return the value of UDS_HOURSE.name
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.name
     *
     * @param name the value for UDS_HOURSE.name
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.tdsy
     *
     * @return the value of UDS_HOURSE.tdsy
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getTdsy() {
        return tdsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.tdsy
     *
     * @param tdsy the value for UDS_HOURSE.tdsy
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTdsy(String tdsy) {
        this.tdsy = tdsy == null ? null : tdsy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.cb
     *
     * @return the value of UDS_HOURSE.cb
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getCb() {
        return cb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.cb
     *
     * @param cb the value for UDS_HOURSE.cb
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCb(String cb) {
        this.cb = cb == null ? null : cb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.jg
     *
     * @return the value of UDS_HOURSE.jg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.jg
     *
     * @param jg the value for UDS_HOURSE.jg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setJg(String jg) {
        this.jg = jg == null ? null : jg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.zcs
     *
     * @return the value of UDS_HOURSE.zcs
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getZcs() {
        return zcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.zcs
     *
     * @param zcs the value for UDS_HOURSE.zcs
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setZcs(String zcs) {
        this.zcs = zcs == null ? null : zcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.pgc
     *
     * @return the value of UDS_HOURSE.pgc
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getPgc() {
        return pgc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.pgc
     *
     * @param pgc the value for UDS_HOURSE.pgc
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPgc(String pgc) {
        this.pgc = pgc == null ? null : pgc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.dh
     *
     * @return the value of UDS_HOURSE.dh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.dh
     *
     * @param dh the value for UDS_HOURSE.dh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.tn
     *
     * @return the value of UDS_HOURSE.tn
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getTn() {
        return tn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.tn
     *
     * @param tn the value for UDS_HOURSE.tn
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTn(String tn) {
        this.tn = tn == null ? null : tn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.ft
     *
     * @return the value of UDS_HOURSE.ft
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getFt() {
        return ft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.ft
     *
     * @param ft the value for UDS_HOURSE.ft
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setFt(String ft) {
        this.ft = ft == null ? null : ft.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.zy
     *
     * @return the value of UDS_HOURSE.zy
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.zy
     *
     * @param zy the value for UDS_HOURSE.zy
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.cg
     *
     * @return the value of UDS_HOURSE.cg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getCg() {
        return cg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.cg
     *
     * @param cg the value for UDS_HOURSE.cg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCg(String cg) {
        this.cg = cg == null ? null : cg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.cx
     *
     * @return the value of UDS_HOURSE.cx
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getCx() {
        return cx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.cx
     *
     * @param cx the value for UDS_HOURSE.cx
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCx(String cx) {
        this.cx = cx == null ? null : cx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.jw
     *
     * @return the value of UDS_HOURSE.jw
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getJw() {
        return jw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.jw
     *
     * @param jw the value for UDS_HOURSE.jw
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setJw(String jw) {
        this.jw = jw == null ? null : jw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.zx
     *
     * @return the value of UDS_HOURSE.zx
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getZx() {
        return zx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.zx
     *
     * @param zx the value for UDS_HOURSE.zx
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setZx(String zx) {
        this.zx = zx == null ? null : zx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.pm
     *
     * @return the value of UDS_HOURSE.pm
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getPm() {
        return pm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.pm
     *
     * @param pm the value for UDS_HOURSE.pm
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPm(String pm) {
        this.pm = pm == null ? null : pm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.wg
     *
     * @return the value of UDS_HOURSE.wg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getWg() {
        return wg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.wg
     *
     * @param wg the value for UDS_HOURSE.wg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setWg(String wg) {
        this.wg = wg == null ? null : wg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.dt
     *
     * @return the value of UDS_HOURSE.dt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getDt() {
        return dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.dt
     *
     * @param dt the value for UDS_HOURSE.dt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDt(String dt) {
        this.dt = dt == null ? null : dt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.jt
     *
     * @return the value of UDS_HOURSE.jt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getJt() {
        return jt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.jt
     *
     * @param jt the value for UDS_HOURSE.jt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setJt(String jt) {
        this.jt = jt == null ? null : jt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.lyhj
     *
     * @return the value of UDS_HOURSE.lyhj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getLyhj() {
        return lyhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.lyhj
     *
     * @param lyhj the value for UDS_HOURSE.lyhj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setLyhj(String lyhj) {
        this.lyhj = lyhj == null ? null : lyhj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.gg
     *
     * @return the value of UDS_HOURSE.gg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGg() {
        return gg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.gg
     *
     * @param gg the value for UDS_HOURSE.gg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGg(String gg) {
        this.gg = gg == null ? null : gg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.wq
     *
     * @return the value of UDS_HOURSE.wq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getWq() {
        return wq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.wq
     *
     * @param wq the value for UDS_HOURSE.wq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setWq(String wq) {
        this.wq = wq == null ? null : wq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.nq
     *
     * @return the value of UDS_HOURSE.nq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getNq() {
        return nq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.nq
     *
     * @param nq the value for UDS_HOURSE.nq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setNq(String nq) {
        this.nq = nq == null ? null : nq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.dm
     *
     * @return the value of UDS_HOURSE.dm
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getDm() {
        return dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.dm
     *
     * @param dm the value for UDS_HOURSE.dm
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDm(String dm) {
        this.dm = dm == null ? null : dm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.thb
     *
     * @return the value of UDS_HOURSE.thb
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getThb() {
        return thb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.thb
     *
     * @param thb the value for UDS_HOURSE.thb
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setThb(String thb) {
        this.thb = thb == null ? null : thb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.mc
     *
     * @return the value of UDS_HOURSE.mc
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.mc
     *
     * @param mc the value for UDS_HOURSE.mc
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.wsj
     *
     * @return the value of UDS_HOURSE.wsj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getWsj() {
        return wsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.wsj
     *
     * @param wsj the value for UDS_HOURSE.wsj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setWsj(String wsj) {
        this.wsj = wsj == null ? null : wsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.ltj
     *
     * @return the value of UDS_HOURSE.ltj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getLtj() {
        return ltj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.ltj
     *
     * @param ltj the value for UDS_HOURSE.ltj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setLtj(String ltj) {
        this.ltj = ltj == null ? null : ltj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.ss
     *
     * @return the value of UDS_HOURSE.ss
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getSs() {
        return ss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.ss
     *
     * @param ss the value for UDS_HOURSE.ss
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setSs(String ss) {
        this.ss = ss == null ? null : ss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.bxfx
     *
     * @return the value of UDS_HOURSE.bxfx
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getBxfx() {
        return bxfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.bxfx
     *
     * @param bxfx the value for UDS_HOURSE.bxfx
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBxfx(String bxfx) {
        this.bxfx = bxfx == null ? null : bxfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.bz
     *
     * @return the value of UDS_HOURSE.bz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.bz
     *
     * @param bz the value for UDS_HOURSE.bz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.bzReport
     *
     * @return the value of UDS_HOURSE.bzReport
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getBzreport() {
        return bzreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.bzReport
     *
     * @param bzreport the value for UDS_HOURSE.bzReport
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBzreport(String bzreport) {
        this.bzreport = bzreport == null ? null : bzreport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.DefinedData1
     *
     * @return the value of UDS_HOURSE.DefinedData1
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getDefineddata1() {
        return defineddata1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.DefinedData1
     *
     * @param defineddata1 the value for UDS_HOURSE.DefinedData1
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDefineddata1(String defineddata1) {
        this.defineddata1 = defineddata1 == null ? null : defineddata1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.DefinedData2
     *
     * @return the value of UDS_HOURSE.DefinedData2
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getDefineddata2() {
        return defineddata2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.DefinedData2
     *
     * @param defineddata2 the value for UDS_HOURSE.DefinedData2
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDefineddata2(String defineddata2) {
        this.defineddata2 = defineddata2 == null ? null : defineddata2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.DefinedData3
     *
     * @return the value of UDS_HOURSE.DefinedData3
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getDefineddata3() {
        return defineddata3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.DefinedData3
     *
     * @param defineddata3 the value for UDS_HOURSE.DefinedData3
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDefineddata3(String defineddata3) {
        this.defineddata3 = defineddata3 == null ? null : defineddata3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.XmlData
     *
     * @return the value of UDS_HOURSE.XmlData
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getXmldata() {
        return xmldata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.XmlData
     *
     * @param xmldata the value for UDS_HOURSE.XmlData
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setXmldata(String xmldata) {
        this.xmldata = xmldata == null ? null : xmldata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_HOURSE.Pm_Structure
     *
     * @return the value of UDS_HOURSE.Pm_Structure
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getPmStructure() {
        return pmStructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_HOURSE.Pm_Structure
     *
     * @param pmStructure the value for UDS_HOURSE.Pm_Structure
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPmStructure(String pmStructure) {
        this.pmStructure = pmStructure == null ? null : pmStructure.trim();
    }
}