package com.spring.mpvue.springbootmpvue.sqlserver.po;

public class UdsRealestate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.PK_UDS_Task_gjd_ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer pkUdsTaskGjdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.REALESTATETYPEID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer realestatetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.appraisalType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer appraisaltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_dz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsDz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.location
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.city
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.area
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_gjff
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsGjff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.cqr
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String cqr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.gyqr
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gyqr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.zh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String zh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.tfdh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String tfdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.xz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String xz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.tdyt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String tdyt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.yt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String yt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_sf
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double rsSf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_crj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double rsCrj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.qsly
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String qsly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double rsPgzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double rsDj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_mj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsMj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.mjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String mjbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_tdmj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsTdmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.tdmjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String tdmjbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_gAside1
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsGaside1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_gAside2
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsGaside2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_gAside3
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsGaside3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.priorpay
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer priorpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.priorpayRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String priorpayremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.CompletedDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String completeddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.LandTerminationDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String landterminationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.TakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer takethewhole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.CalcTakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer calctakethewhole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.RemainYears
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String remainyears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_Land_dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double rsLandDj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_Land_pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double rsLandPgzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_Build_dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double rsBuildDj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.Rs_Build_pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double rsBuildPgzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.rs_type
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.rs_property
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.rs_gjffRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String rsGjffremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.jzwpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double jzwpgzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.tdpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double tdpgzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.IsEstateBulk
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Boolean isestatebulk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.FirstQuotation
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer firstquotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.orderNum
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDS_REALESTATE.ValuationProxy
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String valuationproxy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.ID
     *
     * @return the value of UDS_REALESTATE.ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.ID
     *
     * @param id the value for UDS_REALESTATE.ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.PK_UDS_Task_gjd_ID
     *
     * @return the value of UDS_REALESTATE.PK_UDS_Task_gjd_ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getPkUdsTaskGjdId() {
        return pkUdsTaskGjdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.PK_UDS_Task_gjd_ID
     *
     * @param pkUdsTaskGjdId the value for UDS_REALESTATE.PK_UDS_Task_gjd_ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPkUdsTaskGjdId(Integer pkUdsTaskGjdId) {
        this.pkUdsTaskGjdId = pkUdsTaskGjdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.REALESTATETYPEID
     *
     * @return the value of UDS_REALESTATE.REALESTATETYPEID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getRealestatetypeid() {
        return realestatetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.REALESTATETYPEID
     *
     * @param realestatetypeid the value for UDS_REALESTATE.REALESTATETYPEID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRealestatetypeid(Integer realestatetypeid) {
        this.realestatetypeid = realestatetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.appraisalType
     *
     * @return the value of UDS_REALESTATE.appraisalType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getAppraisaltype() {
        return appraisaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.appraisalType
     *
     * @param appraisaltype the value for UDS_REALESTATE.appraisalType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setAppraisaltype(Integer appraisaltype) {
        this.appraisaltype = appraisaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_dz
     *
     * @return the value of UDS_REALESTATE.Rs_dz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsDz() {
        return rsDz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_dz
     *
     * @param rsDz the value for UDS_REALESTATE.Rs_dz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsDz(String rsDz) {
        this.rsDz = rsDz == null ? null : rsDz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.location
     *
     * @return the value of UDS_REALESTATE.location
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.location
     *
     * @param location the value for UDS_REALESTATE.location
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.city
     *
     * @return the value of UDS_REALESTATE.city
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.city
     *
     * @param city the value for UDS_REALESTATE.city
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.area
     *
     * @return the value of UDS_REALESTATE.area
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.area
     *
     * @param area the value for UDS_REALESTATE.area
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_gjff
     *
     * @return the value of UDS_REALESTATE.Rs_gjff
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsGjff() {
        return rsGjff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_gjff
     *
     * @param rsGjff the value for UDS_REALESTATE.Rs_gjff
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsGjff(String rsGjff) {
        this.rsGjff = rsGjff == null ? null : rsGjff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.cqr
     *
     * @return the value of UDS_REALESTATE.cqr
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getCqr() {
        return cqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.cqr
     *
     * @param cqr the value for UDS_REALESTATE.cqr
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCqr(String cqr) {
        this.cqr = cqr == null ? null : cqr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.gyqr
     *
     * @return the value of UDS_REALESTATE.gyqr
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGyqr() {
        return gyqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.gyqr
     *
     * @param gyqr the value for UDS_REALESTATE.gyqr
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGyqr(String gyqr) {
        this.gyqr = gyqr == null ? null : gyqr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.zh
     *
     * @return the value of UDS_REALESTATE.zh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getZh() {
        return zh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.zh
     *
     * @param zh the value for UDS_REALESTATE.zh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setZh(String zh) {
        this.zh = zh == null ? null : zh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.tfdh
     *
     * @return the value of UDS_REALESTATE.tfdh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getTfdh() {
        return tfdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.tfdh
     *
     * @param tfdh the value for UDS_REALESTATE.tfdh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTfdh(String tfdh) {
        this.tfdh = tfdh == null ? null : tfdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.xz
     *
     * @return the value of UDS_REALESTATE.xz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getXz() {
        return xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.xz
     *
     * @param xz the value for UDS_REALESTATE.xz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setXz(String xz) {
        this.xz = xz == null ? null : xz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.tdyt
     *
     * @return the value of UDS_REALESTATE.tdyt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getTdyt() {
        return tdyt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.tdyt
     *
     * @param tdyt the value for UDS_REALESTATE.tdyt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTdyt(String tdyt) {
        this.tdyt = tdyt == null ? null : tdyt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.yt
     *
     * @return the value of UDS_REALESTATE.yt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getYt() {
        return yt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.yt
     *
     * @param yt the value for UDS_REALESTATE.yt
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setYt(String yt) {
        this.yt = yt == null ? null : yt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_sf
     *
     * @return the value of UDS_REALESTATE.Rs_sf
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getRsSf() {
        return rsSf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_sf
     *
     * @param rsSf the value for UDS_REALESTATE.Rs_sf
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsSf(Double rsSf) {
        this.rsSf = rsSf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_crj
     *
     * @return the value of UDS_REALESTATE.Rs_crj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getRsCrj() {
        return rsCrj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_crj
     *
     * @param rsCrj the value for UDS_REALESTATE.Rs_crj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsCrj(Double rsCrj) {
        this.rsCrj = rsCrj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.qsly
     *
     * @return the value of UDS_REALESTATE.qsly
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getQsly() {
        return qsly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.qsly
     *
     * @param qsly the value for UDS_REALESTATE.qsly
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setQsly(String qsly) {
        this.qsly = qsly == null ? null : qsly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_pgzz
     *
     * @return the value of UDS_REALESTATE.Rs_pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getRsPgzz() {
        return rsPgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_pgzz
     *
     * @param rsPgzz the value for UDS_REALESTATE.Rs_pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsPgzz(Double rsPgzz) {
        this.rsPgzz = rsPgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_dj
     *
     * @return the value of UDS_REALESTATE.Rs_dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getRsDj() {
        return rsDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_dj
     *
     * @param rsDj the value for UDS_REALESTATE.Rs_dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsDj(Double rsDj) {
        this.rsDj = rsDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_mj
     *
     * @return the value of UDS_REALESTATE.Rs_mj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsMj() {
        return rsMj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_mj
     *
     * @param rsMj the value for UDS_REALESTATE.Rs_mj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsMj(String rsMj) {
        this.rsMj = rsMj == null ? null : rsMj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.mjbz
     *
     * @return the value of UDS_REALESTATE.mjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getMjbz() {
        return mjbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.mjbz
     *
     * @param mjbz the value for UDS_REALESTATE.mjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setMjbz(String mjbz) {
        this.mjbz = mjbz == null ? null : mjbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_tdmj
     *
     * @return the value of UDS_REALESTATE.Rs_tdmj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsTdmj() {
        return rsTdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_tdmj
     *
     * @param rsTdmj the value for UDS_REALESTATE.Rs_tdmj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsTdmj(String rsTdmj) {
        this.rsTdmj = rsTdmj == null ? null : rsTdmj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.tdmjbz
     *
     * @return the value of UDS_REALESTATE.tdmjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getTdmjbz() {
        return tdmjbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.tdmjbz
     *
     * @param tdmjbz the value for UDS_REALESTATE.tdmjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTdmjbz(String tdmjbz) {
        this.tdmjbz = tdmjbz == null ? null : tdmjbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_gAside1
     *
     * @return the value of UDS_REALESTATE.Rs_gAside1
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsGaside1() {
        return rsGaside1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_gAside1
     *
     * @param rsGaside1 the value for UDS_REALESTATE.Rs_gAside1
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsGaside1(String rsGaside1) {
        this.rsGaside1 = rsGaside1 == null ? null : rsGaside1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_gAside2
     *
     * @return the value of UDS_REALESTATE.Rs_gAside2
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsGaside2() {
        return rsGaside2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_gAside2
     *
     * @param rsGaside2 the value for UDS_REALESTATE.Rs_gAside2
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsGaside2(String rsGaside2) {
        this.rsGaside2 = rsGaside2 == null ? null : rsGaside2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_gAside3
     *
     * @return the value of UDS_REALESTATE.Rs_gAside3
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsGaside3() {
        return rsGaside3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_gAside3
     *
     * @param rsGaside3 the value for UDS_REALESTATE.Rs_gAside3
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsGaside3(String rsGaside3) {
        this.rsGaside3 = rsGaside3 == null ? null : rsGaside3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.priorpay
     *
     * @return the value of UDS_REALESTATE.priorpay
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getPriorpay() {
        return priorpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.priorpay
     *
     * @param priorpay the value for UDS_REALESTATE.priorpay
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPriorpay(Integer priorpay) {
        this.priorpay = priorpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.priorpayRemark
     *
     * @return the value of UDS_REALESTATE.priorpayRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getPriorpayremark() {
        return priorpayremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.priorpayRemark
     *
     * @param priorpayremark the value for UDS_REALESTATE.priorpayRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPriorpayremark(String priorpayremark) {
        this.priorpayremark = priorpayremark == null ? null : priorpayremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.CompletedDate
     *
     * @return the value of UDS_REALESTATE.CompletedDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getCompleteddate() {
        return completeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.CompletedDate
     *
     * @param completeddate the value for UDS_REALESTATE.CompletedDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCompleteddate(String completeddate) {
        this.completeddate = completeddate == null ? null : completeddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.LandTerminationDate
     *
     * @return the value of UDS_REALESTATE.LandTerminationDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getLandterminationdate() {
        return landterminationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.LandTerminationDate
     *
     * @param landterminationdate the value for UDS_REALESTATE.LandTerminationDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setLandterminationdate(String landterminationdate) {
        this.landterminationdate = landterminationdate == null ? null : landterminationdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.TakeTheWhole
     *
     * @return the value of UDS_REALESTATE.TakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getTakethewhole() {
        return takethewhole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.TakeTheWhole
     *
     * @param takethewhole the value for UDS_REALESTATE.TakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTakethewhole(Integer takethewhole) {
        this.takethewhole = takethewhole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.CalcTakeTheWhole
     *
     * @return the value of UDS_REALESTATE.CalcTakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getCalctakethewhole() {
        return calctakethewhole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.CalcTakeTheWhole
     *
     * @param calctakethewhole the value for UDS_REALESTATE.CalcTakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCalctakethewhole(Integer calctakethewhole) {
        this.calctakethewhole = calctakethewhole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.RemainYears
     *
     * @return the value of UDS_REALESTATE.RemainYears
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRemainyears() {
        return remainyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.RemainYears
     *
     * @param remainyears the value for UDS_REALESTATE.RemainYears
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRemainyears(String remainyears) {
        this.remainyears = remainyears == null ? null : remainyears.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_Land_dj
     *
     * @return the value of UDS_REALESTATE.Rs_Land_dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getRsLandDj() {
        return rsLandDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_Land_dj
     *
     * @param rsLandDj the value for UDS_REALESTATE.Rs_Land_dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsLandDj(Double rsLandDj) {
        this.rsLandDj = rsLandDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_Land_pgzz
     *
     * @return the value of UDS_REALESTATE.Rs_Land_pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getRsLandPgzz() {
        return rsLandPgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_Land_pgzz
     *
     * @param rsLandPgzz the value for UDS_REALESTATE.Rs_Land_pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsLandPgzz(Double rsLandPgzz) {
        this.rsLandPgzz = rsLandPgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_Build_dj
     *
     * @return the value of UDS_REALESTATE.Rs_Build_dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getRsBuildDj() {
        return rsBuildDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_Build_dj
     *
     * @param rsBuildDj the value for UDS_REALESTATE.Rs_Build_dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsBuildDj(Double rsBuildDj) {
        this.rsBuildDj = rsBuildDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.Rs_Build_pgzz
     *
     * @return the value of UDS_REALESTATE.Rs_Build_pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getRsBuildPgzz() {
        return rsBuildPgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.Rs_Build_pgzz
     *
     * @param rsBuildPgzz the value for UDS_REALESTATE.Rs_Build_pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsBuildPgzz(Double rsBuildPgzz) {
        this.rsBuildPgzz = rsBuildPgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.rs_type
     *
     * @return the value of UDS_REALESTATE.rs_type
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsType() {
        return rsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.rs_type
     *
     * @param rsType the value for UDS_REALESTATE.rs_type
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsType(String rsType) {
        this.rsType = rsType == null ? null : rsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.rs_property
     *
     * @return the value of UDS_REALESTATE.rs_property
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsProperty() {
        return rsProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.rs_property
     *
     * @param rsProperty the value for UDS_REALESTATE.rs_property
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsProperty(String rsProperty) {
        this.rsProperty = rsProperty == null ? null : rsProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.rs_gjffRemark
     *
     * @return the value of UDS_REALESTATE.rs_gjffRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getRsGjffremark() {
        return rsGjffremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.rs_gjffRemark
     *
     * @param rsGjffremark the value for UDS_REALESTATE.rs_gjffRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setRsGjffremark(String rsGjffremark) {
        this.rsGjffremark = rsGjffremark == null ? null : rsGjffremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.jzwpgzz
     *
     * @return the value of UDS_REALESTATE.jzwpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getJzwpgzz() {
        return jzwpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.jzwpgzz
     *
     * @param jzwpgzz the value for UDS_REALESTATE.jzwpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setJzwpgzz(Double jzwpgzz) {
        this.jzwpgzz = jzwpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.tdpgzz
     *
     * @return the value of UDS_REALESTATE.tdpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getTdpgzz() {
        return tdpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.tdpgzz
     *
     * @param tdpgzz the value for UDS_REALESTATE.tdpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTdpgzz(Double tdpgzz) {
        this.tdpgzz = tdpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.IsEstateBulk
     *
     * @return the value of UDS_REALESTATE.IsEstateBulk
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Boolean getIsestatebulk() {
        return isestatebulk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.IsEstateBulk
     *
     * @param isestatebulk the value for UDS_REALESTATE.IsEstateBulk
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setIsestatebulk(Boolean isestatebulk) {
        this.isestatebulk = isestatebulk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.FirstQuotation
     *
     * @return the value of UDS_REALESTATE.FirstQuotation
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getFirstquotation() {
        return firstquotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.FirstQuotation
     *
     * @param firstquotation the value for UDS_REALESTATE.FirstQuotation
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setFirstquotation(Integer firstquotation) {
        this.firstquotation = firstquotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.orderNum
     *
     * @return the value of UDS_REALESTATE.orderNum
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.orderNum
     *
     * @param ordernum the value for UDS_REALESTATE.orderNum
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDS_REALESTATE.ValuationProxy
     *
     * @return the value of UDS_REALESTATE.ValuationProxy
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getValuationproxy() {
        return valuationproxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDS_REALESTATE.ValuationProxy
     *
     * @param valuationproxy the value for UDS_REALESTATE.ValuationProxy
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setValuationproxy(String valuationproxy) {
        this.valuationproxy = valuationproxy == null ? null : valuationproxy.trim();
    }
}