package com.spring.mpvue.springbootmpvue.sqlserver.po;

import java.util.Date;

public class UdsTaskGjd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gjdID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer gjdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.xmu_id
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer xmuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.bgdj_follow_ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer bgdjFollowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.cpbh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String cpbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.bgbh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String bgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.moban
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Byte moban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.appraisalType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer appraisaltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.ztsm
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer ztsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.OprationDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Date oprationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.Approver
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String approver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.Maker
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String maker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.dz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.value
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gjry
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gjry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.bum
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String bum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.SignatureAppraisers
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String signatureappraisers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gjmd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gjmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gjsd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Date gjsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.cprq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Date cprq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.bgrq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Date bgrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double pgzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double dj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.mj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String mj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.tdmj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String tdmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.tdmjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String tdmjbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.jsbg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Boolean jsbg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gjff
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gjff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.wtf
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String wtf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.mjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String mjbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gAside1
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gaside1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gAside2
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gaside2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gAside3
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gaside3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.sf
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double sf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.crj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double crj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.MakerType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer makertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.ArchivingProgress
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer archivingprogress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.DeliverProgress
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer deliverprogress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.DeliverMark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String delivermark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.FinanceProgress
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer financeprogress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.isExplore
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer isexplore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.priorpay
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer priorpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.priorpayRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String priorpayremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.TakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer takethewhole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.CalcTakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer calctakethewhole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.OtherTemplateID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer othertemplateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gjszch
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gjszch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.SignedAppraisers
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String signedappraisers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.MarketDj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double marketdj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.MarketPgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double marketpgzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.ReportType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer reporttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.backInvalid
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer backinvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.invalidReason
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String invalidreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.AppraisalTagetType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String appraisaltagettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gjffRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gjffremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.OneLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String onelevelapprovalcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.TwoLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String twolevelapprovalcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.ThreeLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String threelevelapprovalcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.FourLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String fourlevelapprovalcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.jzwpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double jzwpgzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.tdpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Double tdpgzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.aprroveDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Date aprrovedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.SendNum
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String sendnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.arrange
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer arrange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.PrintDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String printdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.BeforeApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String beforeapprovalcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.FirstApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String firstapprover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.SecondApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String secondapprover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.ThridApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String thridapprover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.FourthApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String fourthapprover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.LockingPeople
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String lockingpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.gjdGuid
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String gjdguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.CommissionID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Integer commissionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.SendTime
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uds_task_gjd.wordTempIDstr
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    private String wordtempidstr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gjdID
     *
     * @return the value of uds_task_gjd.gjdID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getGjdid() {
        return gjdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gjdID
     *
     * @param gjdid the value for uds_task_gjd.gjdID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGjdid(Integer gjdid) {
        this.gjdid = gjdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.xmu_id
     *
     * @return the value of uds_task_gjd.xmu_id
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getXmuId() {
        return xmuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.xmu_id
     *
     * @param xmuId the value for uds_task_gjd.xmu_id
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setXmuId(Integer xmuId) {
        this.xmuId = xmuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.bgdj_follow_ID
     *
     * @return the value of uds_task_gjd.bgdj_follow_ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getBgdjFollowId() {
        return bgdjFollowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.bgdj_follow_ID
     *
     * @param bgdjFollowId the value for uds_task_gjd.bgdj_follow_ID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBgdjFollowId(Integer bgdjFollowId) {
        this.bgdjFollowId = bgdjFollowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.cpbh
     *
     * @return the value of uds_task_gjd.cpbh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getCpbh() {
        return cpbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.cpbh
     *
     * @param cpbh the value for uds_task_gjd.cpbh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCpbh(String cpbh) {
        this.cpbh = cpbh == null ? null : cpbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.bgbh
     *
     * @return the value of uds_task_gjd.bgbh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getBgbh() {
        return bgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.bgbh
     *
     * @param bgbh the value for uds_task_gjd.bgbh
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBgbh(String bgbh) {
        this.bgbh = bgbh == null ? null : bgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.moban
     *
     * @return the value of uds_task_gjd.moban
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Byte getMoban() {
        return moban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.moban
     *
     * @param moban the value for uds_task_gjd.moban
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setMoban(Byte moban) {
        this.moban = moban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.appraisalType
     *
     * @return the value of uds_task_gjd.appraisalType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getAppraisaltype() {
        return appraisaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.appraisalType
     *
     * @param appraisaltype the value for uds_task_gjd.appraisalType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setAppraisaltype(Integer appraisaltype) {
        this.appraisaltype = appraisaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.ztsm
     *
     * @return the value of uds_task_gjd.ztsm
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getZtsm() {
        return ztsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.ztsm
     *
     * @param ztsm the value for uds_task_gjd.ztsm
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setZtsm(Integer ztsm) {
        this.ztsm = ztsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.OprationDate
     *
     * @return the value of uds_task_gjd.OprationDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Date getOprationdate() {
        return oprationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.OprationDate
     *
     * @param oprationdate the value for uds_task_gjd.OprationDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setOprationdate(Date oprationdate) {
        this.oprationdate = oprationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.Approver
     *
     * @return the value of uds_task_gjd.Approver
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getApprover() {
        return approver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.Approver
     *
     * @param approver the value for uds_task_gjd.Approver
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setApprover(String approver) {
        this.approver = approver == null ? null : approver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.Maker
     *
     * @return the value of uds_task_gjd.Maker
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getMaker() {
        return maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.Maker
     *
     * @param maker the value for uds_task_gjd.Maker
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setMaker(String maker) {
        this.maker = maker == null ? null : maker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.dz
     *
     * @return the value of uds_task_gjd.dz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.dz
     *
     * @param dz the value for uds_task_gjd.dz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDz(String dz) {
        this.dz = dz == null ? null : dz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.value
     *
     * @return the value of uds_task_gjd.value
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.value
     *
     * @param value the value for uds_task_gjd.value
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gjry
     *
     * @return the value of uds_task_gjd.gjry
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGjry() {
        return gjry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gjry
     *
     * @param gjry the value for uds_task_gjd.gjry
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGjry(String gjry) {
        this.gjry = gjry == null ? null : gjry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.bum
     *
     * @return the value of uds_task_gjd.bum
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getBum() {
        return bum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.bum
     *
     * @param bum the value for uds_task_gjd.bum
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBum(String bum) {
        this.bum = bum == null ? null : bum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.SignatureAppraisers
     *
     * @return the value of uds_task_gjd.SignatureAppraisers
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getSignatureappraisers() {
        return signatureappraisers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.SignatureAppraisers
     *
     * @param signatureappraisers the value for uds_task_gjd.SignatureAppraisers
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setSignatureappraisers(String signatureappraisers) {
        this.signatureappraisers = signatureappraisers == null ? null : signatureappraisers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gjmd
     *
     * @return the value of uds_task_gjd.gjmd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGjmd() {
        return gjmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gjmd
     *
     * @param gjmd the value for uds_task_gjd.gjmd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGjmd(String gjmd) {
        this.gjmd = gjmd == null ? null : gjmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gjsd
     *
     * @return the value of uds_task_gjd.gjsd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Date getGjsd() {
        return gjsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gjsd
     *
     * @param gjsd the value for uds_task_gjd.gjsd
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGjsd(Date gjsd) {
        this.gjsd = gjsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.cprq
     *
     * @return the value of uds_task_gjd.cprq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Date getCprq() {
        return cprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.cprq
     *
     * @param cprq the value for uds_task_gjd.cprq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCprq(Date cprq) {
        this.cprq = cprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.bgrq
     *
     * @return the value of uds_task_gjd.bgrq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Date getBgrq() {
        return bgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.bgrq
     *
     * @param bgrq the value for uds_task_gjd.bgrq
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBgrq(Date bgrq) {
        this.bgrq = bgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.pgzz
     *
     * @return the value of uds_task_gjd.pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getPgzz() {
        return pgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.pgzz
     *
     * @param pgzz the value for uds_task_gjd.pgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPgzz(Double pgzz) {
        this.pgzz = pgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.dj
     *
     * @return the value of uds_task_gjd.dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getDj() {
        return dj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.dj
     *
     * @param dj the value for uds_task_gjd.dj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDj(Double dj) {
        this.dj = dj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.mj
     *
     * @return the value of uds_task_gjd.mj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getMj() {
        return mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.mj
     *
     * @param mj the value for uds_task_gjd.mj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setMj(String mj) {
        this.mj = mj == null ? null : mj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.tdmj
     *
     * @return the value of uds_task_gjd.tdmj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getTdmj() {
        return tdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.tdmj
     *
     * @param tdmj the value for uds_task_gjd.tdmj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTdmj(String tdmj) {
        this.tdmj = tdmj == null ? null : tdmj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.tdmjbz
     *
     * @return the value of uds_task_gjd.tdmjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getTdmjbz() {
        return tdmjbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.tdmjbz
     *
     * @param tdmjbz the value for uds_task_gjd.tdmjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTdmjbz(String tdmjbz) {
        this.tdmjbz = tdmjbz == null ? null : tdmjbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.jsbg
     *
     * @return the value of uds_task_gjd.jsbg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Boolean getJsbg() {
        return jsbg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.jsbg
     *
     * @param jsbg the value for uds_task_gjd.jsbg
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setJsbg(Boolean jsbg) {
        this.jsbg = jsbg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gjff
     *
     * @return the value of uds_task_gjd.gjff
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGjff() {
        return gjff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gjff
     *
     * @param gjff the value for uds_task_gjd.gjff
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGjff(String gjff) {
        this.gjff = gjff == null ? null : gjff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.wtf
     *
     * @return the value of uds_task_gjd.wtf
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getWtf() {
        return wtf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.wtf
     *
     * @param wtf the value for uds_task_gjd.wtf
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setWtf(String wtf) {
        this.wtf = wtf == null ? null : wtf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.mjbz
     *
     * @return the value of uds_task_gjd.mjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getMjbz() {
        return mjbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.mjbz
     *
     * @param mjbz the value for uds_task_gjd.mjbz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setMjbz(String mjbz) {
        this.mjbz = mjbz == null ? null : mjbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gAside1
     *
     * @return the value of uds_task_gjd.gAside1
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGaside1() {
        return gaside1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gAside1
     *
     * @param gaside1 the value for uds_task_gjd.gAside1
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGaside1(String gaside1) {
        this.gaside1 = gaside1 == null ? null : gaside1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gAside2
     *
     * @return the value of uds_task_gjd.gAside2
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGaside2() {
        return gaside2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gAside2
     *
     * @param gaside2 the value for uds_task_gjd.gAside2
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGaside2(String gaside2) {
        this.gaside2 = gaside2 == null ? null : gaside2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gAside3
     *
     * @return the value of uds_task_gjd.gAside3
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGaside3() {
        return gaside3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gAside3
     *
     * @param gaside3 the value for uds_task_gjd.gAside3
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGaside3(String gaside3) {
        this.gaside3 = gaside3 == null ? null : gaside3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.sf
     *
     * @return the value of uds_task_gjd.sf
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getSf() {
        return sf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.sf
     *
     * @param sf the value for uds_task_gjd.sf
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setSf(Double sf) {
        this.sf = sf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.crj
     *
     * @return the value of uds_task_gjd.crj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getCrj() {
        return crj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.crj
     *
     * @param crj the value for uds_task_gjd.crj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCrj(Double crj) {
        this.crj = crj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.MakerType
     *
     * @return the value of uds_task_gjd.MakerType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getMakertype() {
        return makertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.MakerType
     *
     * @param makertype the value for uds_task_gjd.MakerType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setMakertype(Integer makertype) {
        this.makertype = makertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.ArchivingProgress
     *
     * @return the value of uds_task_gjd.ArchivingProgress
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getArchivingprogress() {
        return archivingprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.ArchivingProgress
     *
     * @param archivingprogress the value for uds_task_gjd.ArchivingProgress
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setArchivingprogress(Integer archivingprogress) {
        this.archivingprogress = archivingprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.DeliverProgress
     *
     * @return the value of uds_task_gjd.DeliverProgress
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getDeliverprogress() {
        return deliverprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.DeliverProgress
     *
     * @param deliverprogress the value for uds_task_gjd.DeliverProgress
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDeliverprogress(Integer deliverprogress) {
        this.deliverprogress = deliverprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.DeliverMark
     *
     * @return the value of uds_task_gjd.DeliverMark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getDelivermark() {
        return delivermark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.DeliverMark
     *
     * @param delivermark the value for uds_task_gjd.DeliverMark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setDelivermark(String delivermark) {
        this.delivermark = delivermark == null ? null : delivermark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.FinanceProgress
     *
     * @return the value of uds_task_gjd.FinanceProgress
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getFinanceprogress() {
        return financeprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.FinanceProgress
     *
     * @param financeprogress the value for uds_task_gjd.FinanceProgress
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setFinanceprogress(Integer financeprogress) {
        this.financeprogress = financeprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.isExplore
     *
     * @return the value of uds_task_gjd.isExplore
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getIsexplore() {
        return isexplore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.isExplore
     *
     * @param isexplore the value for uds_task_gjd.isExplore
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setIsexplore(Integer isexplore) {
        this.isexplore = isexplore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.priorpay
     *
     * @return the value of uds_task_gjd.priorpay
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getPriorpay() {
        return priorpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.priorpay
     *
     * @param priorpay the value for uds_task_gjd.priorpay
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPriorpay(Integer priorpay) {
        this.priorpay = priorpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.priorpayRemark
     *
     * @return the value of uds_task_gjd.priorpayRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getPriorpayremark() {
        return priorpayremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.priorpayRemark
     *
     * @param priorpayremark the value for uds_task_gjd.priorpayRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPriorpayremark(String priorpayremark) {
        this.priorpayremark = priorpayremark == null ? null : priorpayremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.TakeTheWhole
     *
     * @return the value of uds_task_gjd.TakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getTakethewhole() {
        return takethewhole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.TakeTheWhole
     *
     * @param takethewhole the value for uds_task_gjd.TakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTakethewhole(Integer takethewhole) {
        this.takethewhole = takethewhole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.CalcTakeTheWhole
     *
     * @return the value of uds_task_gjd.CalcTakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getCalctakethewhole() {
        return calctakethewhole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.CalcTakeTheWhole
     *
     * @param calctakethewhole the value for uds_task_gjd.CalcTakeTheWhole
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCalctakethewhole(Integer calctakethewhole) {
        this.calctakethewhole = calctakethewhole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.OtherTemplateID
     *
     * @return the value of uds_task_gjd.OtherTemplateID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getOthertemplateid() {
        return othertemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.OtherTemplateID
     *
     * @param othertemplateid the value for uds_task_gjd.OtherTemplateID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setOthertemplateid(Integer othertemplateid) {
        this.othertemplateid = othertemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gjszch
     *
     * @return the value of uds_task_gjd.gjszch
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGjszch() {
        return gjszch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gjszch
     *
     * @param gjszch the value for uds_task_gjd.gjszch
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGjszch(String gjszch) {
        this.gjszch = gjszch == null ? null : gjszch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.SignedAppraisers
     *
     * @return the value of uds_task_gjd.SignedAppraisers
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getSignedappraisers() {
        return signedappraisers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.SignedAppraisers
     *
     * @param signedappraisers the value for uds_task_gjd.SignedAppraisers
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setSignedappraisers(String signedappraisers) {
        this.signedappraisers = signedappraisers == null ? null : signedappraisers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.MarketDj
     *
     * @return the value of uds_task_gjd.MarketDj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getMarketdj() {
        return marketdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.MarketDj
     *
     * @param marketdj the value for uds_task_gjd.MarketDj
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setMarketdj(Double marketdj) {
        this.marketdj = marketdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.MarketPgzz
     *
     * @return the value of uds_task_gjd.MarketPgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getMarketpgzz() {
        return marketpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.MarketPgzz
     *
     * @param marketpgzz the value for uds_task_gjd.MarketPgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setMarketpgzz(Double marketpgzz) {
        this.marketpgzz = marketpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.ReportType
     *
     * @return the value of uds_task_gjd.ReportType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getReporttype() {
        return reporttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.ReportType
     *
     * @param reporttype the value for uds_task_gjd.ReportType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setReporttype(Integer reporttype) {
        this.reporttype = reporttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.backInvalid
     *
     * @return the value of uds_task_gjd.backInvalid
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getBackinvalid() {
        return backinvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.backInvalid
     *
     * @param backinvalid the value for uds_task_gjd.backInvalid
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBackinvalid(Integer backinvalid) {
        this.backinvalid = backinvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.invalidReason
     *
     * @return the value of uds_task_gjd.invalidReason
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getInvalidreason() {
        return invalidreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.invalidReason
     *
     * @param invalidreason the value for uds_task_gjd.invalidReason
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setInvalidreason(String invalidreason) {
        this.invalidreason = invalidreason == null ? null : invalidreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.AppraisalTagetType
     *
     * @return the value of uds_task_gjd.AppraisalTagetType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getAppraisaltagettype() {
        return appraisaltagettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.AppraisalTagetType
     *
     * @param appraisaltagettype the value for uds_task_gjd.AppraisalTagetType
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setAppraisaltagettype(String appraisaltagettype) {
        this.appraisaltagettype = appraisaltagettype == null ? null : appraisaltagettype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gjffRemark
     *
     * @return the value of uds_task_gjd.gjffRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGjffremark() {
        return gjffremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gjffRemark
     *
     * @param gjffremark the value for uds_task_gjd.gjffRemark
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGjffremark(String gjffremark) {
        this.gjffremark = gjffremark == null ? null : gjffremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.OneLevelApprovalContent
     *
     * @return the value of uds_task_gjd.OneLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getOnelevelapprovalcontent() {
        return onelevelapprovalcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.OneLevelApprovalContent
     *
     * @param onelevelapprovalcontent the value for uds_task_gjd.OneLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setOnelevelapprovalcontent(String onelevelapprovalcontent) {
        this.onelevelapprovalcontent = onelevelapprovalcontent == null ? null : onelevelapprovalcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.TwoLevelApprovalContent
     *
     * @return the value of uds_task_gjd.TwoLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getTwolevelapprovalcontent() {
        return twolevelapprovalcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.TwoLevelApprovalContent
     *
     * @param twolevelapprovalcontent the value for uds_task_gjd.TwoLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTwolevelapprovalcontent(String twolevelapprovalcontent) {
        this.twolevelapprovalcontent = twolevelapprovalcontent == null ? null : twolevelapprovalcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.ThreeLevelApprovalContent
     *
     * @return the value of uds_task_gjd.ThreeLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getThreelevelapprovalcontent() {
        return threelevelapprovalcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.ThreeLevelApprovalContent
     *
     * @param threelevelapprovalcontent the value for uds_task_gjd.ThreeLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setThreelevelapprovalcontent(String threelevelapprovalcontent) {
        this.threelevelapprovalcontent = threelevelapprovalcontent == null ? null : threelevelapprovalcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.FourLevelApprovalContent
     *
     * @return the value of uds_task_gjd.FourLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getFourlevelapprovalcontent() {
        return fourlevelapprovalcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.FourLevelApprovalContent
     *
     * @param fourlevelapprovalcontent the value for uds_task_gjd.FourLevelApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setFourlevelapprovalcontent(String fourlevelapprovalcontent) {
        this.fourlevelapprovalcontent = fourlevelapprovalcontent == null ? null : fourlevelapprovalcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.jzwpgzz
     *
     * @return the value of uds_task_gjd.jzwpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getJzwpgzz() {
        return jzwpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.jzwpgzz
     *
     * @param jzwpgzz the value for uds_task_gjd.jzwpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setJzwpgzz(Double jzwpgzz) {
        this.jzwpgzz = jzwpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.tdpgzz
     *
     * @return the value of uds_task_gjd.tdpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Double getTdpgzz() {
        return tdpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.tdpgzz
     *
     * @param tdpgzz the value for uds_task_gjd.tdpgzz
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setTdpgzz(Double tdpgzz) {
        this.tdpgzz = tdpgzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.aprroveDate
     *
     * @return the value of uds_task_gjd.aprroveDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Date getAprrovedate() {
        return aprrovedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.aprroveDate
     *
     * @param aprrovedate the value for uds_task_gjd.aprroveDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setAprrovedate(Date aprrovedate) {
        this.aprrovedate = aprrovedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.SendNum
     *
     * @return the value of uds_task_gjd.SendNum
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getSendnum() {
        return sendnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.SendNum
     *
     * @param sendnum the value for uds_task_gjd.SendNum
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setSendnum(String sendnum) {
        this.sendnum = sendnum == null ? null : sendnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.arrange
     *
     * @return the value of uds_task_gjd.arrange
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getArrange() {
        return arrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.arrange
     *
     * @param arrange the value for uds_task_gjd.arrange
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setArrange(Integer arrange) {
        this.arrange = arrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.PrintDate
     *
     * @return the value of uds_task_gjd.PrintDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getPrintdate() {
        return printdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.PrintDate
     *
     * @param printdate the value for uds_task_gjd.PrintDate
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setPrintdate(String printdate) {
        this.printdate = printdate == null ? null : printdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.BeforeApprovalContent
     *
     * @return the value of uds_task_gjd.BeforeApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getBeforeapprovalcontent() {
        return beforeapprovalcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.BeforeApprovalContent
     *
     * @param beforeapprovalcontent the value for uds_task_gjd.BeforeApprovalContent
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setBeforeapprovalcontent(String beforeapprovalcontent) {
        this.beforeapprovalcontent = beforeapprovalcontent == null ? null : beforeapprovalcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.FirstApprover
     *
     * @return the value of uds_task_gjd.FirstApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getFirstapprover() {
        return firstapprover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.FirstApprover
     *
     * @param firstapprover the value for uds_task_gjd.FirstApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setFirstapprover(String firstapprover) {
        this.firstapprover = firstapprover == null ? null : firstapprover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.SecondApprover
     *
     * @return the value of uds_task_gjd.SecondApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getSecondapprover() {
        return secondapprover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.SecondApprover
     *
     * @param secondapprover the value for uds_task_gjd.SecondApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setSecondapprover(String secondapprover) {
        this.secondapprover = secondapprover == null ? null : secondapprover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.ThridApprover
     *
     * @return the value of uds_task_gjd.ThridApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getThridapprover() {
        return thridapprover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.ThridApprover
     *
     * @param thridapprover the value for uds_task_gjd.ThridApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setThridapprover(String thridapprover) {
        this.thridapprover = thridapprover == null ? null : thridapprover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.FourthApprover
     *
     * @return the value of uds_task_gjd.FourthApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getFourthapprover() {
        return fourthapprover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.FourthApprover
     *
     * @param fourthapprover the value for uds_task_gjd.FourthApprover
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setFourthapprover(String fourthapprover) {
        this.fourthapprover = fourthapprover == null ? null : fourthapprover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.LockingPeople
     *
     * @return the value of uds_task_gjd.LockingPeople
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getLockingpeople() {
        return lockingpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.LockingPeople
     *
     * @param lockingpeople the value for uds_task_gjd.LockingPeople
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setLockingpeople(String lockingpeople) {
        this.lockingpeople = lockingpeople == null ? null : lockingpeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.gjdGuid
     *
     * @return the value of uds_task_gjd.gjdGuid
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getGjdguid() {
        return gjdguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.gjdGuid
     *
     * @param gjdguid the value for uds_task_gjd.gjdGuid
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setGjdguid(String gjdguid) {
        this.gjdguid = gjdguid == null ? null : gjdguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.CommissionID
     *
     * @return the value of uds_task_gjd.CommissionID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Integer getCommissionid() {
        return commissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.CommissionID
     *
     * @param commissionid the value for uds_task_gjd.CommissionID
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setCommissionid(Integer commissionid) {
        this.commissionid = commissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.SendTime
     *
     * @return the value of uds_task_gjd.SendTime
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.SendTime
     *
     * @param sendtime the value for uds_task_gjd.SendTime
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uds_task_gjd.wordTempIDstr
     *
     * @return the value of uds_task_gjd.wordTempIDstr
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public String getWordtempidstr() {
        return wordtempidstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uds_task_gjd.wordTempIDstr
     *
     * @param wordtempidstr the value for uds_task_gjd.wordTempIDstr
     *
     * @mbggenerated Mon Sep 10 21:28:50 CST 2018
     */
    public void setWordtempidstr(String wordtempidstr) {
        this.wordtempidstr = wordtempidstr == null ? null : wordtempidstr.trim();
    }
}